TI-113 modelo turno
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #115
Opened 2024-07-06 14:02 UTC by RubenDelgadoPareja

En esta PR hemos añadido el código necesario para plasmar la idea del turno del paciente en la espera de urgencias.
El código consiste en la clase Turno con atributos que la definen como el paciente al que pertenece el turno, el riesgo que tiene,
el tiempo que se creó y la posición en la cola.
Este código ayuda a completar la capa de dominio del proyecto y aporta valor a la HU https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/issues/19.

2024-07-08 08:27 UTC, JJ requested changes
Esto ha mejorado mucho, pero debes intentar tener en cuenta buenas prácticas y, sobre todo, los principios de domain driven design para diseñar cada uno de las estructuras de datos con las que vas a trabajar.

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  id: number;
¿Qué hay en la historia de usuario que necesite el id?

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  position: number,
¿La posición en la cola es parte del modelo del turno, o bien es algo que hay que gestionar desde otra entidad porque puede variar durante la vida del objeto?

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +export enum RiskEnum {
¿Has considerado poner esto antes, ya que lo usas en la línea 9? Aunque sintácticamente sea correcto, si lees desde arriba (lo normal) te encuentras con un tipo que no se ha definido

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  CRITICAL = 'CRITICAL',
El hecho de que haya cuatro niveles tiene que venir de una entrevista con el cliente. ¿Es así como se clasifican?

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  readonly __brand = "Turn" as const;
???

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  get id(): number {
¿Estás poniendo todos los getters y setters o solo los que te piden las historias de usuario?

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  private constructor(private readonly props: TurnInputProps) {}
¿Hay alguna razón por la que estés usando "create" en vez del simple `new`? Normalmente se usa este tipo de patrón si estás trabajando con un singleton, pero aquí simplemente estás sustituyendo un constructor por otro que redirecciona al primero. ¿Qué ganas con eso?

2024-07-08 08:27 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  static create(props: TurnInputProps): Turn {
¿Qué tiene que ver esto con la separación de responsabilidades? Además, trata de referirte en todos y cada uno de los mensajes de commit a un issue. No resuelvas problemas que no existen, haciendo referencias a una refactorización que no hay ningún issue que la pida.
SOLID es, en todo caso, una estrategia de diseño que hay que aplicar desde el principio.

2024-07-08 17:35 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +  CRITICAL = 'CRITICAL',
Realmente me he fijado de una página de documentación sobre un triage donde exponen bastantes datos importantes. Dejo el link por aqui https://scielo.isciii.es/scielo.php?script=sci_arttext&pid=S1137-66272010000200008

2024-07-08 17:44 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +  readonly __brand = "Turn" as const;
Es una buena práctica de Typescript, se llama branding y se utiliza para aumentar la seguridad en runtime. Principalmente me gusta ponerlo para suplir el problema que tiene Typescript de que es un lenguaje estructural y no nominativo. Te dejo un post que lo explica bien https://prosopo.io/articles/typescript-branding/. Pero si consideras que es innecesario se elimina

2024-07-08 17:51 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +  static create(props: TurnInputProps): Turn {
He mencionado SOLID porque esta práctica cumple con la S de Single responsability , la intención de detrás de la separación de los inputs y el modelo es que la interfaz TurnInputProps se encargue de los datos y el modelo o clase Turn se encargue de la lógica. Quizás es innecesario o un poco precipitado añadirlo ya ?

2024-07-08 17:58 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +  position: number,
Realmente se gestionará desde la misma cola, era por tener una referencia desde este modelo. Lo borraré cuando me tope con ese problema ya lo resolveré

2024-07-08 18:02 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  CRITICAL = 'CRITICAL',
Por favor, incluye el enlace a esto en la historia de usuario y también en la documentación; sería conveniente, en temas de este estilo, que incluyeras la documentación, es decir, que escribieras la memoria a la vez.

2024-07-08 18:12 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +  private constructor(private readonly props: TurnInputProps) {}
La principal intención es restringir el uso del new directamente y saltarnos que las posibles reglas de validacion a la hora de crear una instancia del objeto. Pero quizás también es adelantarnos al problema que se dará cuando tengamos las validaciones

2024-07-08 18:13 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  readonly __brand = "Turn" as const;
me parece muy bien que explores artículos y demás, siempre aprenderás más que haciendo lo que ya sabes; yo he aprendido bastante leyendo el artículo y te lo agradezco. Sin embargo
1. Ahora mismo estás modelizando el dominio del problema, y siempre se debe crear el mínimo código necesario para el próximo PMV. ¿Crees que esto es mínimo?
2. En desarrollo ágil debes hacer siempre lo que pida un issue que plantee un problema. Si un código no resuelve un problema, es deuda técnica. 
3. En ese sentido, no parece que vayas a tener otra clase que sea estructuralmente similar a `Turn`. Si la hubiera, se abre un issue, y se puede probar esta solución (como otra cualquiera).
4. Tampoco parece que estés haciendo exactamente lo que comenta en el artículo. Si te fijas, usa `Symbol` para generar un ID único a partir del nombre que uses como brand, y ese ID único lo usa como nombre del campo. Fíjate que usa la sintaxis `[brand]`, que sirve para asignar un nombre contenido en una variable a un campo. 
5. Finalmente, en el artículo lo están usando en tipos (`type`) no interfaces. En realidad son prácticamente intercambiables, y por otro lado usan un genérico para asignar un brand a cualquier tipo que lo necesite.

En resumen: es genial que busques cosas nuevas y trates de aplicar buenas prácticas, porque eso te permite aprender. Pero en este caso deberías considerar la necesidad de aplicarla, y de hacerlo así.

Te recuerdo por otro lado que yo no te puedo decir lo que es necesario o no, porque es tu proyecto. Es la metodología de trabajo la que te tiene que decir si algo es correcto o no, siempre mirando al final a las historias de usuario.

2024-07-08 18:14 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  private constructor(private readonly props: TurnInputProps) {}
Te digo lo mismo que en el otro caso. Si estás resolviendo un problema, plantea el problema claramente y propón este código como solución. No tengo claro qué es "saltarse las posibles reglas de validación", pero si efectivamente es un problema, crea un issue y por supuesto un test donde se vea que se hace efectivamente lo que dice el issue, resolviendo el problema.

2024-07-08 18:18 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  static create(props: TurnInputProps): Turn {
Lo que dices es bastante razonable. Pero en general
1. Los objetos valor no tienen más lógica que la de validar su creción.
2. Un interfaz no tiene en realidad ninguna responsabilidad, por lo que Turn tendría al final *toda* la responsabilidad ya que debe implementarlo todo.
3. Lo que estás haciendo aquí es separar la definición de las variables de instancia de la definición de la clase. Podría ser razonable en un problema complejo, donde combines diferentes interfaces para cada una de las clases. Pero aquí en realidad sólo estás creando un identificador adicional. Más importante que SOLID es KISS: Keep it simple, Sam. ¿Crees que esto aporta algún valor sobre simplemente definir las variables de instancia?

2024-07-08 18:19 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +  readonly __brand = "Turn" as const;
Me parece razonable, intentaré seguir la metodología todavía me cuesta

2024-07-08 18:22 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  readonly __brand = "Turn" as const;
Realmente, al final te simplifica mucho el trabajo y sobre todo el trabajo futuro sobre el código...

2024-07-08 18:31 UTC, JJ requested changes
por favor, dale una pequeña vuelta, que ya casi está.

2024-07-08 18:31 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +  private constructor(
Si el constructor es privado, ¿cómo lo construyes?

2024-07-08 18:31 UTC, JJ commented on src/modules/turn/domain/turn.ts
> +import { DateTime } from 'luxon';
Realmente deberíais usar CoPilot de forma crítica y no incluir directamente lo que sale. En este caso, hay dos cuestiones.
1. Typescript tiene un tipo Date estándar, que es posible que sea suficiente en este caso.
2. Has incluido una dependencia, pero no está añadida al gestor de dependencias.

Aparte de esto, en general las dependencias conviene justificarlas en la documentación. Y por otro lado, aunque a este nivel no harían falta tests unitarios, sí deberías incluir un workflow que al menos comprobara la sintaxis o hiciera lint del código para detectar algún problema como este.

2024-07-10 16:48 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +import { DateTime } from 'luxon';
Justamente en este caso si que se añadió luxon al paquete de dependencias. Abriré una issue refactorizando / eliminando todas las dependencias que no se usan. (Tengo luxon, uuid, axios y nest.js). Sin embargo, había añadido luxon porque el tipo Date.js es bastante pobre y lo están reworkeando (por lo que tengo entendido) pero quizas con Date.js me vasta para el proyecto. 
En caso, de que Date.js entorpezca cambiaré a luxon

2024-07-10 17:06 UTC, RubenDelgadoPareja commented on src/modules/turn/domain/turn.ts
> +import { DateTime } from 'luxon';
Sobre el workflow, tengo ESLint configurado para cada vez que se hace un push corra el CI con un task

2024-07-10 20:32 UTC, merged