Reescribir los objetivos del proyecto
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #24
Opened 2023-01-16 00:25 UTC by RubenDelgadoPareja

Se ha simplificado y rediseñado el objetivo principal para que sea más realista, al igual que con el apartado de proyecto a futuro
Este pull request hace referencia a las issues #16 y #8

2023-02-08 06:38 UTC, JJ commented
Perdón por la tardanza; si no os corrijo una cosa a la semana o así dadme un toque, por favor. Gracias por el recordatorio.

2023-02-08 06:43 UTC, JJ requested changes
Siempre que se resuelve el problema en ingeniería, se resuelve el problema *de alguien*. Tienes que identificar bien quienes son los clientes, porque a partir de eso se va a configurar el producto en sí.

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\textbf{Crear el triage inteligente de las consultas médicas}. El objetivo del sistema es minimizar las repercusiones negativas
El objetivo no puede ser la descripción de un producto, tiene que incluir los problemas que resuelve. En concreto, tendrías que decir
* Qué hace el triage inteligente
* Como se minimizan las listas de espera saturadas
* Cómo se va a priorizar mejor las personas con mayores riesgos.

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
>  El sistema informática consistirá en un triage de consultas médicas ; el triage en el ámbito de la sanidad es un proceso que permite gestionar
typo: informática.

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El triage tiene un gran potencial que no se aprovecha en los sistemas de citas de la sanidad actual.
Tienes que enunciar antes cuál es el sistema de citas actual.

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El principal proyecto a futuro sería integrar el triage como tal a los sistemas instaurados en la sanidad como si se tratase de
Una librería de código, ¿en qué sistema?

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +una librería de código. Además puedrían desarrollarse los siguientes puntos:
Por favor, incluye un comprobador ortográfico en las herramientas de IC

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item Aplicar la aplicación para consultas especializadas (Neurología, Urología, Ginecología \dots)
Todo esto son casos de uso que tienen que convertirse en historias de usuario.

2023-02-08 06:43 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item Construir e integrar un plugin para acceder a las recetas de los medicamentos de una consulta
Plugin ¿de qué?

2023-02-21 06:38 UTC, JJ requested changes
Has mejorado algo la descripción, pero tienes que tratar de mejorar la expresión escrita (que es una parte fundamental de la evaluación) y el comentario que no se ha contemplado. La parte de "proyecto a futuro" sería mejor que se quedara para otro PR en el que se describan los hitos.

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +tenemos que lidiar a día de hoy, construyendo una aplicación de citas médicas el cual tiene integrado un sistema de triage.
una aplicación ... integrado. Trata de mantener la concordancia de género y número. No sé si el textidote mencionado lo hace, si no tendrás que hacerlo a base de releer.
(Es el tipo de cosas que te quita puntos en #13 )

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Además, estará centrado para el empleo de todas las personas y sanitarios, haciendo hincapié en la accesibilidad de la app.
"centrado para el empleo" -> trata de reescribirlo. "Todas las personas _y_ sanitarios": igual. Los sanitarios también son personas.
Por otro lado, si es un requisito funcional, debe ser parte de las historias de usuario.

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\textbf{Crear el triage inteligente de las consultas médicas}. El objetivo del sistema es minimizar las repercusiones negativas
:arrow_up:

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El triage inteligente en consultas médicas consiste en clasificar los pacientes en diferentes estados de riesgo y priorizar las citas
¿Cuando tiene lugar? ¿Cuando se llama por teléfono?

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La asignación de riesgo se realizará mediante un formulario que deben rellenar el paciente al registrarse, esta prioridad provisional
Estás describiendo la implementación. Eso es algo que tiene que salir del proceso de desarrollo. Por otro lado, estás hablando de un momento determinado, "al registrarse". Por eso es esencial que aclares las historias de usuario, y cuándo va a tener lugar ese triage.

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +se comprobará y modificará si es necesario por los sanitarios. De este modo se establece un riesgo dinámico.
Si el riesgo es dinámico, ¿la cita también puede cambiar después de la primer asignación?
Tienes que describir el contexto claramente al principio, qué es lo que se considera triage, y cómo se haría de forma independiente de la aplicación.

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El triage tiene un gran potencial que no se aprovecha en los sistemas de citas de la sanidad actual, durante todo el desarollo
. antes de durante.

2023-02-21 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
>  \subsection{Proyecto a futuro}
No existe el proyecto a futuro o a pasado. Existen ciertos milestones y productos mínimamente viables, que tendrás tiempo de desarrollar durante el TFG o no. Por eso es esencial que describas los diferentes productos mínimamente viables; lo puedes hacer ahora o no, pero es esencial como esqueleto del desarrollo.

2023-03-27 07:21 UTC, JJ requested changes
Por favor, revisa todos los comentarios que se hayan hecho y cambia la línea sobre la que se hagan o, si se ha cambiado algo en otra línea, explica en qué commit se ha hecho y resuelve.

2023-03-27 07:21 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\textbf{Crear el triage inteligente de las consultas médicas}. El objetivo del sistema es minimizar las repercusiones negativas
No has contestado a esto... Mira en la solapa "files changed" que puede haber comentarios que no hayas revisado.

2023-03-27 07:21 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El triage inteligente en consultas médicas consiste en clasificar los pacientes en diferentes estados de riesgo y priorizar las citas
:arrow_up:

2023-03-27 07:21 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La asignación de riesgo se realizará mediante un formulario que deben rellenar el paciente al registrarse, esta prioridad provisional
:arrow_up:

2023-03-28 05:51 UTC, JJ approved these changes
Voy a optar por aprobar, aunque los objetivos precisos tendrías que afinarlos un poco. En todo caso, los objetivos deben tener su propio PR, así que ahí se puede afinar. :clap:

2023-03-28 05:51 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La asignación de riesgo se realizará mediante un formulario que deben rellenar el paciente al registrarse, esta prioridad
¿No será "a partir de" en vez de "mediante"? Mediante significaría que el riesgo lo rellena el propio usuario.

2023-03-28 05:51 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +se comprobará y podrá ser modificado por los sanitarios. Esto es necesario, ya que, la mayoría de pacientes aumentarán de riesgo
¿Cuando será comprobada y modificada por los sanitarios?

2023-03-28 05:51 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El triage tiene un gran potencial que no se aprovecha en los sistemas de citas de la sanidad actual, durante todo el desarrollo
; y no coma

2023-03-28 05:51 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +el sistema se comparará con el sistema de citas \href{https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/clicsalud/pages/portada.jsf?caducada=1}{ClicSalud+},
sistema está dos veces.

2023-03-28 05:51 UTC, JJ commented on doc/secciones/01_introduccion.tex
> + al igual que los tiempos medios de espera de los pacientes para afirmar que el desarrollo del sistema implica una mejora.
Tendrías que expresar este objetivo primero con más énfasis y segundo más claramente. No sé si los tiempos medios cambiarán; lo que cambiará será el tiempo medio *según el riergo*, ¿no?

2023-03-30 07:05 UTC, JJ approved these changes
:+1:

2023-03-30 07:05 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La asignación de riesgo se realizará a partir un formulario que deben rellenar el paciente al registrarse, esta prioridad
a partir _de_. Como te dije, sería conveniente que incluyérais textidote, que también tiene comprobación gramatical.

2023-03-30 07:05 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +la mayoría de pacientes aumentarán de riesgo con los años y con las enfermedades que padezcan.
Quizás sería conveniente que explicaras claramente qué es lo que significa "riesgo" en este caso, y cómo lo vas a representar. Aunque en este PR no hace falta, tendrás que explicarlo bien en la memoria, y yo te diría que sería mejor que te informaras con publicaciones o con un profesional de atención primaria.

2023-04-04 16:49 UTC, merged

2023-04-04 16:49 UTC, RubenDelgadoPareja commented
closes #16 #8