11 perfiles de usuario y escenarios de los clientes del triage inteligente user journey
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #27
Opened 2023-02-26 23:21 UTC by RubenDelgadoPareja

2023-03-02 06:50 UTC, JJ requested changes
En general está bien y es lo que se busca, pero la estructura y donde lo enmarcas es importante.

2023-03-02 06:50 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +\chapter{Users Journeys}\label{anexo}
No sé si merece la pena que le pongas todo un capítulo aparte. Además, debería ir en cursiva porque son palabras extranjeras y es *user journeys*; el plural en inglés va sólo en la última palabra.

2023-03-02 06:50 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    \item \textbf{Nombre y apellidos: } Samuel Tena Sánchez
Si vas a usar personas con nombre y apellidos, tienes que usar la metodología de *personas* para definirlas. Mira aquí por ejemplo https://www.interaction-design.org/literature/article/personas-why-and-how-you-should-use-them

2023-03-02 06:52 UTC, JJ commented
Recuerda también que todo PR tiene que estar avanzando un issue, que a la vez desarrollará una historia de usuario; en este caso posiblemente la #13. También tiene que estar, issue y PR, en un milestone.

2023-03-06 10:15 UTC, JJ approved these changes
Vamos a aceptarlo por lo pronto, aunque me da la impresión de que tiene excesivos detalles por un lado y por otro lado le falta cosas como ¿qué pasa si le dan la cita después del viaje? Siempre se puede refinar.
También debes dejar claro en los PRs cuál es el ámbito. Si el ámbito es "todas" las HUs, se queda un poco corto.

2023-03-06 10:15 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    regalarle un viaje a Francia por Navidad. Sin embargo ha comenzado a enfermar por la bajada
No se enferma por la bajada de temperaturas, hombre...

2023-03-20 11:13 UTC, JJ requested changes
Te aconsejaría que le echaras un vistazo [a este artículo])https://www.linkedin.com/pulse/comenzando-con-un-trabajo-fin-de-gradom%2525C3%2525A1ster-%2525C3%2525A1gil-juan-j-merelo%3FtrackingId=GE7H2FZuQayVzupdjG7zLA%253D%253D/?trackingId=GE7H2FZuQayVzupdjG7zLA%3D%3D). El *design thinking* te puede ayudar a definir bien el problema con el que estás tratando.
Por otro lado, sería conveniente que, en un PR aparte, configuraras el corrector ortográfico y lo mergearas antes de continuar con este. Como os he comentado, es parte del milestone 0.

2023-03-20 11:13 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    su cumpleaños.
NO entiendo muy bien esta HU desde el punto de vista de la lógica de negocio. ¿Qué implicaciones tiene en la lógica de negocio? ¿Que pueda no dar citas? ¿O que pueda recibir cita en la primera fecha que se pueda?
Si lo que quieres decir aquí es que el triage inteligente está juzgando que una fiesta de cumpleaños no es lo suficientemente urgente para dar prioridad a la cita, lo entendería, pero tienes de alguna forma que reflejar eso explícitamente en la historia de usuario.

2023-03-20 11:13 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    \item \textbf{Estudia: } Grado en Medicina
¿Estudia o ha estudiado?

2023-03-20 11:13 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +        \item \textbf{¿Qué espera encontrar en ella?: } Espera encontrar el historial médico del paciente y una interfaz sencilla para establecer el riesgo
Por esto precisamente es por lo que necesitas hacer correctamente esta fase; tienes que definir el problema. Yo entiendo que si se trata de un triage *inteligente* no tendrá que haber ningún tipo de intervención humana en la decisión de si priorizar un paciente o no. Recuerda también que *ahora mismo* los doctores no tienen ninguna decisión en su agenda ni a quién atienden. Si tienen que intervenir en el proceso de cita, es más trabajo y no creo que quieran hacerlo. En todo caso, tendrías que dejar aquí bien claro qué es lo que querría un facultativo de esto y qué tendría que hacer. ¿Decidir cuantas citas al día se dedican a urgentes? ¿Colocar a los urgentes al principio de la sesión para darles más tiempo?
En ingeniería del software conviene siempre conocer bien el problema, y en este caso te aconsejaría hablar con médicos de familia para que te planteen realmente qué problema tienen. Lo que comentas, en concreto, seguro que ya lo tienen: acceder al historial es fácil, e incluso se puede acceder al historial si se tiene consulta privada.

2023-03-20 11:13 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +\subsection{Escenario Azucena Rodriguez}
No dejas claro algo muy importante: *cuándo* se asignaría el riesgo. Resulta razonable que hay una retroalimentación sobre el riesgo declarado o estimado por el paciente cuando se le da la cita, y el que el facultativo percibe cuando efectivamente tiene la cita. Puede, en función de como lo vea, decir si ha exagerado un poco o por el contrario se han minusvalorado los riesgos, pero sería todo lo que el facultativo tendría que hacer. Si tienen ellos que establecer el riesgo (mientras el paciente espera en el teléfono, además), el triage no va a ser muy "inteligente"

2023-04-10 07:14 UTC, JJ requested changes
Sigue habiendo algunos comentarios pendientes. Por favor, revísalos.

2023-04-10 07:14 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    tener un riesgo asignado. Una vez se registra accede a la página principal de la web donde puede
Lo que haga internamente el sistema no es parte de la historia *del usuario*

2023-04-10 07:14 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    medicamentos para poder tratarse antes de su viaje.
Ten en cuenta que estos user journeys son instrumentos precisos para poder solucionar el problema. Aquí introduces un elemento temporal *durante el registro*. Esto quiere decir que no se va a poder solicitar información para evaluar riesgo *en el momento de la cita*
En cualquier caso eso son detalles de implementación que no forman parte de la historia de usuario. Lo que sí forma parte de la historia de usuario sería el hecho de que los factores de riesgo que pueden influir en el triage varíen con el tiempo, o cuáles pueden ser esos factores. Trata de ajustar los user journeys a estos parámetros, por favor.

2023-04-10 07:14 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    \item \textbf{Estudia: } Grado en Medicina
Tampoco conviene que introduzcas elementos irrelevantes. Como te digo arriba, se trata de que los user journeys conduzcan, a través del *design thinking*, a un diseño de la aplicación adecuado al usuario.

2023-04-13 19:30 UTC, RubenDelgadoPareja commented on doc/secciones/08_user-journey.tex
> +    su cumpleaños.
@JJ Tienes razón no tiene mucho sentido añadir otro escenario del mismo usuario, creo que en la anterior puedo reflejar todo lo necesario para que se comprenda el sistema, por lo que voy a eliminarla

2023-04-14 05:44 UTC, JJ requested changes
Mira siempre en la solapa "files" para ver qué comentarios quedan por revisar; hay todavía un par de ellos.

2023-04-14 05:44 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    Azucena es una mujer que ha estudiado la carrera de Medicina y ha estudiado para ser médica de cabecera.
:arrow_up:

2023-04-20 11:56 UTC, JJ requested changes
Te copio aquí uno de los comentarios:

> Recuerda que siempre tiene que haber un beneficio para el usuario que quede claro. Aquí se intuye, pero no queda claro que asignando riesgo va a tener mejor organizadas las citas y va a tener a sus pacientes con riesgo verdadero con citas más cercanas y urgentes. Tendrías que introducir en la historia algo así como "ve que un paciente con mucho riesgo ha recibido la cita el mismo día" o "ve que las citas que tiene han estimado el riesgo cada vez mejor"
> En todo caso, recuerda que todo esto son cosas que hay que programar. A partir de esta historia y la otra tienes que organizar todo el desarrollo.

Es esencial que revises todos los comentarios para que se pueda aprobar el PR.

2023-04-20 11:56 UTC, JJ commented on doc/secciones/08_user-journey.tex
> +    \item \textbf{Estudia: } Grado en Medicina
Sigues sin contestar a estas cosas específicas que te he comentado. Para que "desaparezcan" tienes o bien que modificar o borrar la línea, o si has hecho una modificación en algún otro lugar, "resolver" indicando como se ha hecho.

2023-04-20 12:08 UTC, JJ commented
Tampoco está lanzando el corrector ortográfico. Por favor, comprueba que funcione; si no es así, no puedes fusionar esta rama (ni acabar el milestone)

2023-04-25 05:37 UTC, JJ approved these changes
Voy a aprobarlo porque has tenido en cuenta todas las revisiones, pero en el futuro
1. Los PRs siempre tienen que incluir referencia a uno o varios issues (a su vez, referenciando HUs)
2. No se puede incorporar código sin que pase el corrector ortográfico.

2023-04-25 18:44 UTC, merged