47 añadir framework de prueba al proyecto para mejorar la calidad del código
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #54
Opened 2023-07-24 18:02 UTC by RubenDelgadoPareja

Necesario para completar la tarea #47 
Se ha añadido la gema Rspec para poder correr los test en Ruby , sin embargo es necesario para generar los archivos y correrlos Rails , por lo que seguramente será necesario instalarlo en el repositorio. Además se ha añadido al .git/workflow/pre-commit.yml 
el comando para correr los tests. Este PR se aceptará cuando se puedan crear tests.

2023-07-24 18:09 UTC, JJ requested changes
Recuerda que 
1. Tienes que justificar todas las decisiones en función de las opciones disponibles (una de las rúbricas de evaluación mías y del tribunal). En este sentido has tomado dos: el framework, y usar Docker para pasarlo. Si usas Docker, tienes que montar la infraestructura para generar un nuevo contenedor cada vez que haya un cambio; ¿has considerado simplemente usar un workflow de GitHub? Ruby es uno de los lenguajes que usa por defecto, y seguro que puedes cachear las dependencias. La otra es usar Rubocop...
2. Tienes que enmarcar esto también en el desarrollo del proyecto y por eso en todas las decisiones que tomes debes avanzar la memoria explicando la decisión que has tomado.
3. REalmente no entiendo muy bien qué es overcommit y qué es rubocop aquí y qué papeles tienen
4. Esto se tendría que pasar automáticamente, y debería formar parte del mismo PR.

2023-07-24 18:12 UTC, JJ requested changes
Recuerda también que la elección del IDE es algo que tienes que justificar, quizás antes que esto. Los IDEs deben ayudar a la productividad del usuario.

2023-07-24 18:12 UTC, JJ commented on docker-compose.yml
> +version: '3.1'
No veo la necesidad de usar Docker compose si todo lo que tienes es un único contenedor. En todo caso, las soluciones adoptadas deberías justificarlas en los mensajes de commit.

2023-07-24 18:12 UTC, JJ commented on Gemfile
> +  gem 'overcommit', '~> 0.58.0'
Uf, un framework para ejecutar hooks... Los hooks locales siempre son problemáticos en una organización, y conozco realmente pocas que lo usen. Si lo tienes que ejecutar automáticamente, lo mejor es dejar que GitHub lo haga por ti, soportado si acaso por una configuración compatible del IDE que uses.

2023-07-25 18:51 UTC, RubenDelgadoPareja commented on docker-compose.yml
> +version: '3.1'
Tengo pensado utilizar docker-compose para la futura base de datos y porque utilizando solamente docker se utilizarlo tan bien

2023-07-26 06:15 UTC, JJ commented on docker-compose.yml
> +version: '3.1'
No uses nada para el futuro nada en un PR que es para el presente.

2023-07-27 06:58 UTC, JJ reviewed
No sé si has hecho algún cambio adicional, sólo te añado el comentario sobre `overcommit`

2023-07-27 06:58 UTC, JJ commented on .overcommit.yml
> +# Use this file to configure the Overcommit hooks you wish to use. This will
Incluso aunque uses overcommit, debes configurar un workflow de GitHub para ejecutar los tests, así que en realidad es redundante.

2023-07-31 08:31 UTC, JJ requested changes
Aparte de los problemas técnicos que te comento, hay una serie de problemas de base con el texto que conviene que entiendas bien desde el primer momento. Ánimo que ya queda menos.

2023-07-31 08:31 UTC, JJ commented on Dockerfile
> +FROM ruby:3.0.2
Sigo sin entender la existencia del Dockerfile. Pero *si vas a usarlo*, debes seguir las buenas prácticas en cuanto a
1. Generación de la imagen cuando cambie alguna dependencia
2. Elección de la imagen base
3. Organización de los directorios en la imagen generada
4. Uso de usuarios no privilegiados

En [este objetivo de IV](http://jj.github.io/IV/documentos/proyecto/5.Docker) enlazo más o menos lo necesario para el tema.

2023-07-31 08:31 UTC, JJ commented on Dockerfile
> +RUN apt-get update && apt-get install -y nano
¿Necesitas nano dentro del contenedor?

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Los hitos han sido definidos en GitHub y cada uno de ellos contiene un grupo de \textit{issues} que se corresponden
Enlázalos.

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +con las distintas mejoras que se han ido incorporando al software a lo largo de su desarrollo.
Los hitos son una herramienta para organizar el desarrollo teniendo en cuenta cuál es el objetivo próximo y haciendo sólo lo necesario para alcanzarlo. Para ello, dentro del hito hay que dedicar algo de tiempo a crear los issues que planteen los problemas que hay para alcanzar el próximo PVM, y la metodología te tiene que decir qué issue abordar primero; esto lo tienes que documentar en el TFG.

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\paragraph*{Corrector ortográfico semántico}
¿Semántico? ¿No será gramatical?

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +
Para hacer las cosas un poco mejor, sería mejor que describieras aquí el producto mínimamente viable que se va crear y sus componentes. Las subsecciones deberían tener como título las diferentes partes de ese PMV.
Si no, no se entienden muy bien los títulos. "Memoria" no significa nada. Si el PMV dijera "Capítulos de la memoria metodológicos" se entendería bastante mejor. En todo caso, la memoria no forma estrictamente parte del proyecto, y por tanto estrictamente no sería parte de la "implementación"; la comprobación ortográfica sí, puesto que forma parte de la "preocupación general por la calidad" que #13 evalúa (y del desarrollo ágil)

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\paragraph*{Lenguaje de Programación}
Puedes usar subsubsection

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +He optado por escoger Ruby como el lenguaje principal para desarrollar este trabajo debido a las numerosas ventajas que me ofrece.
No estás diciendo nada en realidad. "Numerosas ventajas" ¿con respecto a qué?

El lenguaje de programación es una de las cosas que menos hay que justificar, pero hay que justificarlo de todas formas.

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +la escritura de código limpio y legible. Cuenta con una gran batería de librerías o gemas que agiliza el desarrollo y permite la
Todos tienen muchas librerías. Sin embargo, si has justificado en metodología que vas a usar desarrollo ágil y código limpio, enlaza esto con lo que hayas dicho antes.

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +implementación rápida de características. Finalmente, nos aporta un framework como Ruby on Rails que favorece el desarrollo ágil que
Ruby on Rails todavía no lo has justificado, y sinceramente un desarrollo MVC va generalmente en contra del desarrollo ágil, porque acopla fuertemente todas las partes del mismo. Cuando lleguemos a la elección del framework ya veremos lo que hacemos, pero por lo pronto puedes decir que cuenta con diferentes bibliotecas para aplicaciones cliente servidor, como por ejemplo...

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Para la automatización de procesos de integración se ha escogido usar los workflows de GitHub, debido a que es un servicio gratuito, fácil de configurar y escalabilidad.
Justifícalo también en el desarrollo ágil. Tienes que tratar de que la memoria apoye las decisiones en decisiones anteriores tomadas, no como si cada una de las cosas las eligieras desde cero.

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +correctamente. También se había sopesado la opción de utilizar una gema llamada \textit{overcommit}. Sin embargo, no se ha escogido porque sería una carga innecesaria del sistema.
A ver, explica las cosas medianamente bien. Primero
1. Qué es la integración continua
2. Qué opciones hay: cliente, servidor
3. Opciones posibles en cada uno de ellos
4. Opción elegida y su justificación.

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\paragraph*{Test unitarios e integración}
Creo que es un poco pronto para esto, pero en fin...

2023-07-31 08:31 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Como framework de pruebas he decidido escoger RSpec por su potencia y simplicidad. Esta herramienta tiene una gran popularidad en el desarrollo
La justificación de las decisiones no es "he elegido esto por esto".
es
1. En mi proyecto, hace falta esto.
2. Las diferentes opciones en este momento son las siguientes, y estas son las diferentes funcionalidades que ofrecen.
3. De todas, cuantitativamente es la mejor esta por tal razón: seguridad, actualización, una serie de cosas.
En [este objetivo](http://jj.github.io/IV/documentos/proyecto/3.Automatizar) de IV explico más o menos como se justifica esta decisión (y prácticamente todas, como el sistema de CI que vayas a alegir e incluso el editor)

2023-07-31 18:03 UTC, RubenDelgadoPareja commented on doc/secciones/06_implementacion.tex
> +
Está definido en la metodología el PMV , voy a añadir una referencia

2023-11-11 17:06 UTC, closed without merging