closes #59 Agregar contenedor de docker, configuracion de ESlint y pr…
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #60
Opened 2023-10-08 18:06 UTC by RubenDelgadoPareja

Se ha añadido configuraciones precisas para poder crear un contenedor de docker y tener las tecnologías de ESlinter y Prettier. 
Este PR es necesario para la issue #59 , se podrá cerrar cuando sea posible crear una imagen de docker con las tecnologias a usar

2023-10-09 05:31 UTC, JJ requested changes
No entiendo muy bien la necesidad de un contenedor Docker en esta fase. No tiene nada que ver con el milestone, ni parece que sea lo mínimo necesario.

2023-10-09 05:31 UTC, JJ commented on Dockerfile
> +FROM node:18.16
¿Por qué necesitas un contenedor Docker? Si lo necesitas, ¿por qué usas esta versión?

2023-10-16 08:59 UTC, JJ commented
No entiendo muy bien el objetivo de este PR ahora mismo. Ya te comenté que en esta fase no es necesario ningún fichero que lance el app. También está en el milestone 1, pero todavía no hemos terminado el cero. Conviene también que cuando hagas algún cambio en el PR cambies el título y el cuerpo.

2023-10-16 09:01 UTC, JJ commented
Si lo que estás poniendo es la configuración de eslint, haz sólo eso. No hace falta que añadas ficheros para probarlo, o al menos no hace falta que los añadas en el repositorio.

2023-10-23 07:33 UTC, JJ commented on src/index.ts
> +import express from 'express'
No entiendo muy bien qué hace esto aquí; ya habías eliminado el otro fichero. Si se trata de ver efectivamente si funciona el workflow, puedes esperar a que se añada algo, no tienes que resolverlo aquí.

2023-10-23 18:13 UTC, RubenDelgadoPareja commented on src/index.ts
> +import express from 'express'
Lo he vuelto a añadir para comprobar que el hook funciona correctamente, pero lo elimino ahora sin problema

2023-10-23 18:17 UTC, RubenDelgadoPareja commented on tsconfig.json
> +    // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */
En principio quiero dejarlos por si en un futuro tengo que cambiar la configuración del typescript del proyecto. Dependiendo de las necesidades que vayan surgiendo quizás cambie  cosas

2023-10-24 05:23 UTC, JJ commented on tsconfig.json
> +    // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */
No creo que lo necesites, pero si lo haces, símplemente consúltalo en algún lugar.

2023-10-30 19:43 UTC, RubenDelgadoPareja commented on tsconfig.json
> +    // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */
De acuerdo , he dejado algunos comentarios, para saber donde visitar la página y donde iría cada linea de config dependiendo a qué afecte

2023-11-01 18:43 UTC, JJ approved these changes
:+1:

2023-11-01 18:44 UTC, JJ commented
(pero no fusiones hasta que no pase el linter)

2023-11-01 18:49 UTC, RubenDelgadoPareja commented
@JJ No va a pasar ese test porque no tenemos archivos .ts para testear. Por eso añadí el archivo comprobé que pasaba el test y luego lo volví a quitar. Lo añadiré de nuevo en el Milestone 1

2023-11-01 18:52 UTC, merged