closes #61. Agregar los workflows para construir y comprobar la documentación de latex
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #63
Opened 2023-10-15 19:02 UTC by RubenDelgadoPareja

Este PR soluciona el problema de la issue #61 , ya que hemos agregado los archivos de config de Github Actions.
Ayuda a completar la HU #13 ya que ayuda a la generación de una documentación libre de errores

2023-10-16 08:40 UTC, JJ requested changes
Aparte de lo dicho, ¿alguna razón por la que hay dos workflows en vez de uno solo? También tienes diferentes razones para lanzarlos.

2023-10-16 08:40 UTC, JJ commented on .github/workflows/build-latex.yml
> +              uses: actions/checkout@v2
Esta versión de checkout está deprecada

2023-10-18 18:59 UTC, RubenDelgadoPareja commented
He decidido agregar la línea `continue-on-error: true` ya que lo indicaba expresamente en la documentación de Textidote
![image](https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/assets/48712946/eac76fde-3dc7-4608-9d32-4bdb74b2efab)
En este link https://github.com/sylvainhalle/textidote

2023-10-19 05:35 UTC, JJ approved these changes
Lo veo bien, salvo detalles que no bloquean.

2023-10-19 05:35 UTC, JJ commented on .github/workflows/build-latex.yml
> +        uses: actions/checkout@v4.1.1
No uses versiones tan específicas. v4 automáticamente equivale a la última minor.

2023-10-19 05:35 UTC, JJ commented on .github/workflows/build-latex.yml
> +        uses: actions/upload-artifact@v3.1.3
= que arriba.

2023-10-19 05:35 UTC, JJ commented on .github/workflows/check-latex.yml
> +        if: success() || failure()
Esto será verdad siempre, ¿no?

2023-10-19 15:54 UTC, merged