PMV del Milestone 0
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #67
Opened 2023-11-12 12:48 UTC by RubenDelgadoPareja

Una vez terminadas cerradas todas las issues del Milestone 0 obtenemos un PVM listo para poder comenzar a programar en nuestro proyecto. Este PR es necesario para pasar al siguiente Milestone y sería como un "despliegue" a producción. 
Necesario para completar la HU #13. Closes #59 #64

2023-11-12 17:10 UTC, JJ requested changes
Varias cosas
1. Debes intentar hacer los PRs mucho más atómicos. Si este es uno en el que has fusionado otros PRs, por favor indica qué específicaente hay que revisar.
2. No sé si travis es una buena elección para nada hoy en día. Si estaba en la plantilla mía, mal por la plantilla, tendré que quitarlo.
3. Trata de organizar un poco los directorios de forma que los ficheros de imágenes, por ejemplo, no estén en el mismo que el Makefile
4. También debería haber un sólo Makefile, es más práctico...

2023-11-13 20:18 UTC, RubenDelgadoPareja commented
> Varias cosas
> 
> 1. Debes intentar hacer los PRs mucho más atómicos. Si este es uno en el que has fusionado otros PRs, por favor indica qué específicaente hay que revisar.
> 2. No sé si travis es una buena elección para nada hoy en día. Si estaba en la plantilla mía, mal por la plantilla, tendré que quitarlo.
> 3. Trata de organizar un poco los directorios de forma que los ficheros de imágenes, por ejemplo, no estén en el mismo que el Makefile
> 4. También debería haber un sólo Makefile, es más práctico...

@JJ  Lo principal que hay que revisar , es que la jerarquía de directorios está correcta y tengo todo lo necesario para comenzar con el Milestone 1 y el modelado del dominio del negocio. Travis venía con tu plantilla del TFG. Aplicaré los cambios que me pides, después de que se mergee esta PR en master tengo que tener un PVM listo para el comienzo de desarrollo del proyecto, esa es la intención de este PR

2023-11-13 20:57 UTC, RubenDelgadoPareja commented
@JJ Esta PR es tan grande porque es el despliegue del Milestone 0 a master (simulándolo como producción). El Makefile está en el directorio /doc para compilar y corregir la documentacion y solamente me aparece uno.

2023-11-14 10:59 UTC, JJ commented
OK, trata de que pase el lint en todo caso y luego lo reviso.

2023-11-14 11:17 UTC, JJ requested changes
Dale una vuelta a los workflows. Recuerda que también el lenguaje que se use es una consecuencia del análisis del problema; en este punto ni siquiera debería ser posible saber que vas a usar TypeScript, salvo que sea un requisito tuyo el usar un lenguaje con tipos.

2023-11-14 11:17 UTC, JJ commented on .github/workflows/build-latex.yml
> +  push:
Deberías limitarlo a los paths en los que realmente esté la memoria. Estos workflows tardan mucho para que se hagan siempre.
También en los pull_requests.

2023-11-14 11:17 UTC, JJ commented on .github/workflows/check-latex.yml
> +on: push
Igual que antes, deberías limitar los paths; y por otro lado, deberías ligar este al anterior, o incluso meterlos en el mismo. Si no pasa la comprobación ortográfica, no merece la pena compilarlo, por ejemplo.
Puedes crear un grupo también si quieres ejecutarlos a la vez para que cancele uno si ha fallado el otro, pero realmente no creo que merezca la pena.

2023-11-14 11:17 UTC, JJ commented on .github/workflows/eslint.yml
> +on: push
Igual, sólo debería lanzarse si has modificado algún fichero por el que tengas que pasar el linter. Si no te va a dar error, como ahora.

2023-11-14 11:17 UTC, JJ commented on .github/workflows/eslint.yml
> +        run: npm install
npm install puede modificar package-lock.json. En CI debe usarse siempre npm ci

2023-11-14 11:17 UTC, JJ commented on .github/workflows/eslint.yml
> +          node-version: 18
No es la última versión estable ahora mismo.

2023-11-14 20:12 UTC, RubenDelgadoPareja reviewed
@JJ  He subido un commit con los cambios en los workflows. El tema de Typescript lo dejaré plasmado en la documentación, será un requisito para asegurar la calidad del código al ser un lenguaje tipado y rígido.

2023-11-15 06:54 UTC, JJ requested changes
Los paths en los workflows son relativos.
También ten en cuenta que en algunos casos serán extensiones, no directorios; por ejemplo, para linting tendrás que lanzarlo también para los tests.

2023-11-15 06:54 UTC, JJ commented on .github/workflows/build-latex.yml
> +  push:
Resuelve todo lo que hayas hecho, por favor, cierra indicando en el comentario el commit donde se ha hecho

2023-11-15 06:54 UTC, JJ commented on .github/workflows/build-latex.yml
> +      - '/doc/**'
Los caminos son relativos, son caminos del filesystem

2023-11-15 06:54 UTC, JJ commented on .github/workflows/check-latex.yml
> +      - '/doc/**'
Igual, usa caminos relativos.

2023-11-15 06:54 UTC, JJ commented on .github/workflows/eslint.yml
> +      - '/src/**.ts'
Lo mismo.

2023-11-17 00:12 UTC, RubenDelgadoPareja reviewed
@JJ He añadido el cambio en los paths para que sean relativos

2023-11-17 16:32 UTC, JJ approved these changes
:+1:

2023-11-19 09:50 UTC, merged