Agregar tipados personalizados
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #73
Opened 2024-01-10 19:35 UTC by RubenDelgadoPareja

Es necesario implementar tipos personalizados para darle calidad y legibilidad al código.
Además ayudarán a que sea más cómodo de programar
PR necesaria para la HU #13.

2024-01-11 10:12 UTC, JJ commented
En general, deberías hacer PRs contra issues, no directamente contra HUs. En este caso, además, estás hablando de código y lo estás haciendo para el tribunal. El código debería siempre aportar valor al cliente; cómo lo explicas o las elecciones que haces es lo que debería aportar valor al tribunal.
Trata de exponer los problemas que estás tratando de resolver en un issue (que vaya asociado a una HU "de cliente") y reformular el cuerpo de este PR, por favor. En teoría, si reformulas un issue el código deberías reescribirlo, pero vamos a dejarlo así por lo pronto y cuando lo hagas ya veremos.

Ten en cuenta que el objetivo de un PR es que haya otra persona que revise la calidad y adecuación del código para la solución del problema que se ha planteado. En ausencia de la expresión de tal problema, o si dices simplemente que es para satisfacer al tribunal, cualquier cosa es válida, en realidad. No se puede argumentar a favor (o en contra) de cualquier alternativa, lo que va en contra de todos los principios de calidad del software (y de desarrollo ágil, donde lo principal es satisfacer al cliente)

2024-01-12 19:05 UTC, RubenDelgadoPareja commented
> En general, deberías hacer PRs contra issues, no directamente contra HUs. En este caso, además, estás hablando de código y lo estás haciendo para el tribunal. El código debería siempre aportar valor al cliente; cómo lo explicas o las elecciones que haces es lo que debería aportar valor al tribunal. Trata de exponer los problemas que estás tratando de resolver en un issue (que vaya asociado a una HU "de cliente") y reformular el cuerpo de este PR, por favor. En teoría, si reformulas un issue el código deberías reescribirlo, pero vamos a dejarlo así por lo pronto y cuando lo hagas ya veremos.
> 
> Ten en cuenta que el objetivo de un PR es que haya otra persona que revise la calidad y adecuación del código para la solución del problema que se ha planteado. En ausencia de la expresión de tal problema, o si dices simplemente que es para satisfacer al tribunal, cualquier cosa es válida, en realidad. No se puede argumentar a favor (o en contra) de cualquier alternativa, lo que va en contra de todos los principios de calidad del software (y de desarrollo ágil, donde lo principal es satisfacer al cliente)

Entiendo lo que me quieres decir, justamente hay ya una issue para esta PR. Sin embargo , pensaba que era mejor hacer referencia a la HU directamente. Cambio la descripción de la PR

2024-01-15 17:40 UTC, JJ requested changes
No es tanto pedir cambios como que creo que el planteamiento de este PR no va por buen camino. #70 no plantea un problema, y tampoco aporta valor al cliente.
Pero lo principal es que deberías intentar seguir las buenas prácticas en issues, en mensajes de commit y demás.
Hay una parte de este PR que puede ser salvable, que es la parte de definición de errores y excepciones. Pero una vez más, los errores se tienen que diseñar en base a necesidades expecíficas del código y, eventualmente, del cliente.

2024-01-15 17:40 UTC, JJ commented on src/modules/shared/types/either.ts
> +export class Either<L, R> {
Hay varios problemas con este código. 
1. Deberías enlazar realmente el issue. Si es #70, simplemente con la almohadilla lo consigues.
2. Sigue habiendo el problema con #70 que te comenté al principio; está ligado a una HU que no aporta valor al cliente. En general, no vas a crear código para añadir valor al tribunal, como dice #13. Eso significa que al final te vas a encontrar con código que no es evaluable, pero que posiblemente no uses eventualmente para nada.
3. Debes intentar seguir las mejores prácticas en el desarrollo. Tienes un solo commit que abarca muchísimo código, por lo que no queda claro qué es lo que haces para resolver el issue.

Al final, el tema principal es ¿este código, para qué sirve? En ingeniería se trata de emplear eficientemente el tiempo y el esfuerzo y sólo escribir lo que a uno le haga falta.

2024-01-15 19:00 UTC, RubenDelgadoPareja commented on src/modules/shared/types/either.ts
> +export class Either<L, R> {
Disculpa, mas o menos entiendo que el modus operandi es ir avanzando aportando valor al cliente constantemente y cuando nos topemos con algún fallo o veamos que la calidad del código es mala y dificulta el progreso (Nuevo problema) abrir una nueva issue para solucionarla y que esté relacionada a la HU del Tribunal o alguna otra que la desbloquee. Me cuesta todavía tener esta metodología en mente constantemente ...

2024-01-15 19:02 UTC, JJ commented on src/modules/shared/types/either.ts
> +export class Either<L, R> {
En este caso creo que hay una parte salvable, donde defines los errores, pero solo y exclusivamente si realmente resuelven algún problema existente en el código.
El problema con estos tipos personalizados es que puede que los necesites, pero en todo caso tendrán que ser adaptados a tu problema.

2024-01-15 19:04 UTC, RubenDelgadoPareja commented on src/modules/shared/types/either.ts
> +export class Either<L, R> {
De acuerdo , por lo pronto voy a cancelar la PR y a cerrar la issue . Si se da la situación en la que necesite volveré  a añadirlos justificandolo todo. Gracias!

2024-01-15 19:07 UTC, closed without merging