Modelar contexto acotado de Cita
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #75
Opened 2024-01-28 17:22 UTC by RubenDelgadoPareja

Se ha modelado la clase principal de Cita como Entidad (dependiente de un Paciente).
Además se han añadido todos sus Value Objects / Entidades. 
Esta PR es necesaria para satisfacer la HU #13 y #5
El merge de esta PR cierra la issue #72

2024-01-29 12:52 UTC, JJ requested changes
En DDD, antes de hablar de contextos acotados tienes que intentar aplicar el concepto de lenguaje ubicuo, y eso se aborda en los issues. En ese lenguaje ubicuo habrá que ver qué se tiende por Fecha de Cita (y si tiene alguna característica más aparte de ser una fecha). Si eso se deduce a partir del concepto de "prioridad" (necesitaría una discusión un poco más extensa que la que hay en #72, para establecer ese término en el lenguaje ubicuo), debería tener su propio issue. 
En todo caso, el objetivo de los PRs es agrupar diferentes issues, cada uno en su commit, y en cada uno se explica cómo se soluciona el problema indicado en un issue. Un solo commit con un solo issue y un PR con el mismo no permite abordar paso a paso (o issue a issue) dese el punto de vista del revisor cómo se están solucionando los problemas, y por tanto no permiten llevar a cabo la metodología de forma fluida.
Por concretar
1. Debes concretar cada término del lenguaje ubicuo en su propio issue.
2. Cada issue debe tener uno o más commits

2024-01-29 12:52 UTC, JJ commented on src/modules/appointment/domain/appointment-date.ts
> +  // TODO: Add validation to the date, it should be beetween the doctor timetables and patient choices
No es una buena costumbre hacer esto. O haces un issue, y lo resuelves dentro del PR, o no haces nada hasta que no resuelvas eso.

2024-01-29 12:52 UTC, JJ commented on src/modules/appointment/domain/appointment-date.ts
> +export class AppointmentDate extends ValueObject<AppointmentDateProps> {
Me temo que no hay nada en #72 que permita no ya suponer que hay una clase que necesite esto (y no simplemente una fecha en formato nativo TypeScript), sino ni siquiera una fecha.

2024-01-31 17:06 UTC, RubenDelgadoPareja commented
> En DDD, antes de hablar de contextos acotados tienes que intentar aplicar el concepto de lenguaje ubicuo, y eso se aborda en los issues. En ese lenguaje ubicuo habrá que ver qué se tiende por Fecha de Cita (y si tiene alguna característica más aparte de ser una fecha). Si eso se deduce a partir del concepto de "prioridad" (necesitaría una discusión un poco más extensa que la que hay en #72, para establecer ese término en el lenguaje ubicuo), debería tener su propio issue. En todo caso, el objetivo de los PRs es agrupar diferentes issues, cada uno en su commit, y en cada uno se explica cómo se soluciona el problema indicado en un issue. Un solo commit con un solo issue y un PR con el mismo no permite abordar paso a paso (o issue a issue) dese el punto de vista del revisor cómo se están solucionando los problemas, y por tanto no permiten llevar a cabo la metodología de forma fluida. Por concretar
> 
> 1. Debes concretar cada término del lenguaje ubicuo en su propio issue.
> 2. Cada issue debe tener uno o más commits

De que manera procedo entonces ? Cierro esta PR si mergear y lo voy haciendo en pequeñas PRs por cada atributo que vaya sacando del lenguaje ubicuo. Además, cómo aplico el lenguaje ubicuo sin tener unos expertos en el dominio del problema ...

2024-01-31 17:09 UTC, JJ commented
Mira a ver qué parte del código desarrollado se ha hecho realmente resolviendo un problema, y mantenla, el resto me temo que es mejor borrarla.

2024-02-02 08:19 UTC, JJ requested changes
Generalmente se trata de que inicialmente se haga los productos más simples posibles que reunan las características que queremos. Convertir todo en una clase al final conduce a un montón de código y evidentemente deuda técnica, y es más sencillo complicar cuando sea necesario que simplificar cuando acabe uno harto de tanta clase.

2024-02-02 08:19 UTC, JJ commented on src/modules/appointment/domain/appointment-id.ts
> +export class AppointmentId extends Entity<{ value: UniqueEntityID }> {
¿De veras que necesitas una clase para esto?

2024-02-02 08:19 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
> +  get AppointmentDescription(): AppointmentDescription {
¿Necesitas todos los getters?

2024-02-04 16:53 UTC, RubenDelgadoPareja commented on src/modules/appointment/domain/appointment-id.ts
> +export class AppointmentId extends Entity<{ value: UniqueEntityID }> {
Es una práctica común en DDD , ya que forma parte de la clase y es la característica que le otorga una identidad propia. Pero si que se podria añadir a parte ...

2024-02-04 19:10 UTC, JJ commented on src/modules/appointment/domain/appointment-id.ts
> +export class AppointmentId extends Entity<{ value: UniqueEntityID }> {
Una práctica en DDD no puede ponerse por encima del desarrollo ágil, que dice que hay que desarrollar solo y exclusivamente lo que añada valor al cliente. Si se considera que el cliente necesita un ID, hay que buscar la forma más simple de proporcinar el ID en la clase correspondiente.

2024-02-04 20:23 UTC, RubenDelgadoPareja commented on src/modules/appointment/domain/appointment-id.ts
> +export class AppointmentId extends Entity<{ value: UniqueEntityID }> {
De acuerdo , lo cambio entonces . Metodología de trabajo antes que Diseño entiendo

2024-02-07 07:45 UTC, JJ approved these changes
En general, deberías intentar escribir tests incluso para clases tan simples, porque sin los tests no sabes de qué forma están solucionando los problemas del cliente, pero por lo pronto lo vamos a dejar pasar.

2024-02-12 20:44 UTC, merged