INN-77: Definir la separacion del dominio y explicar los conceptos de…
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #79
Opened 2024-02-06 19:48 UTC by RubenDelgadoPareja

Definir lo que es un subdominio y contexto acotado. 
Explicar que cuales son los posibles contextos acotados identificados por el momento. 
Esta PR satisface el problema de la issue #77 ya que conseguimos con el ejemplo dado dividir el dominio del problema .

2024-02-09 08:36 UTC, JJ requested changes
En general, conviene que la documentación esté lo más ligada posible al desarrollo. Si en la fase de desarrollo en la que estás es en la implementación, siempre conviene comentar cómo has aplicado esa metodología al desarrollo, de forma que se entiendan tus decisiones; por otro lado, en el capítulo de metodología, hay que comentar qué tipo de metodologías se pueden usar para pasar del lenguaje de las historias de usuario y del dominio del problema al código. ¿No crees que usar un capítulo específico separa el contenido tanto de su razón de ser como de su aplicación?

2024-02-09 08:36 UTC, JJ commented on doc/secciones/05_diseño.tex
>  \chapter{Diseño Dirigido por el Dominio}
No es habitual tener un capítulo destinado exclusivamente al diseño. Suele haber uno dedicado a la metodología, y dentro de él se puede incluir una sección donde se hable del diseño.

2024-02-09 08:36 UTC, JJ commented on doc/secciones/05_diseño.tex
> +El diseño del software que he decidido aplicar es DDD\textit{(Domain Driven Design)} para enfocar el
En general, "he decidido" es una frase que no da ninguna pista sobre el conocimiento del estudiante del estado del arte y alternativas disponibles, ni de qué criterios se han seguido para elegir esa alternativa y no otra (como, no sé, UML o Rational Rose o las que hayan, que realmente no lo sé). Recuerda que #13 tiene como criterio de evaluación "El estudiante sabe aprovechar las oportunidades" y "El estudiante sabe examinar las diferentes alternativas y justificar sus decisiones". ¿Crees que "he decidido" se considera una documentación adecuada de una decisión?

2024-02-09 08:36 UTC, JJ commented on doc/secciones/05_diseño.tex
> +desarrollo del producto en el dominio del problema, de forma que, el sistema contemple el lenguaje y lógica del negocio.
nunca coma después de "que" relativo. ¿No estás usando textidote para comprobación gramatical?

2024-02-09 08:36 UTC, JJ commented on doc/secciones/05_diseño.tex
> +Este tipo de diseño se centra en los \textit{(stakeholders)} al igual que la metodología ágil, porque requieren una constante comunicación con ellos.
No existe la metodología ágil, existe el desarrollo ágil.

2024-02-09 08:36 UTC, JJ commented on doc/secciones/05_diseño.tex
> +    \item Gestión de Pacientes
¿Por qué las mayúsculas?

2024-02-09 08:36 UTC, JJ commented on doc/secciones/05_diseño.tex
> +Son un tipo de objeto que representa un valor, pero no tiene identidad propia a diferencia de las Entidades.
¿Crees que esta exposición de DDD aporta valor al tribunal? ¿No has considerado hacer un pequeño resumen y comentar cómo lo has aplicado en el capítulo de implementación?

2024-02-10 15:43 UTC, RubenDelgadoPareja commented on doc/secciones/05_diseño.tex
> +El diseño del software que he decidido aplicar es DDD\textit{(Domain Driven Design)} para enfocar el
Entiendo perfectamente que tengo que justificar cada decisión que haya tomado, pero en el caso de escoger Domain Driven Design tu me propusiste aplicarlo y a pesar de que Domain Driven Design no va a relucir en esta situación he decidido escogerlo por aprender un nuevo patrón de diseño tanto en la teoría como en la práctica.

2024-02-13 10:27 UTC, JJ requested changes
La estructura de la memoria es bastante importante, pero también no entrar en detalles de bajo nivel que te pueden exponer a todo tipo de ataques por parte del tribunal.

2024-02-13 10:27 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\section{Diseño}
Tendrías que intentar que todas las secciones de un capítulo o subsecciones de una sección fueran una enumeración de temas similares; una progresión, o una enumeración exhaustiva, y que haya una cierta continuidad entre unos o otros. La sección anterior termina con "Todas las issues"... Pero a continuación empiezas con "El diseño es parte fundamental del desarrollo"
Deberías intentar que un capítulo fuera un poco más como una historia. Para eso tienes la introducción al capítulo, donde tienes que exponer "voy a contar tal cosa, y para ello lo voy a hacer de esta forma, enlazando las diferentes partes". Si esa frase ves que tiene partes incoherentes (como "Voy a hablar de los issues, y luego del diseño" Es que posiblemente tengas que reconsiderar lo que estás escribiendo y cómo lo estás contando. Si no, el #13 no se va a quedar demasiado satisfecho.

2024-02-13 10:27 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +Dentro del Diseño Dirigido por el Dominio debemos abstraer distintos módulos para disgregar el problema en pequeñas partes
¿De veras crees que es necesario entrar a este nivel de detalle? ¿Qué efecto quieres que produzca esto en el tribunal? Una cosa es que muestres que entiendes cómo funciona una metodología (pero donde realmente hay que mostrar que se entiende es en la práctica) y otra contar esa metodología, lo que abre muchos y diferentes ángulos de ataque: puedes tener errores gramaticales, ortográficos, errores en la descripción, que realmente no van a afectar lo que has hecho, pero pueden rebajar la nota que te ponga el tribunal.
Considera, por favor, simplemente hacer una referencia a la metodología que has seguido, citando el libro de Domain Driven Design, una descripción sucinta de en qué consiste la metodología, por qué es ágil, y llamada hacia delante diciendo en qué parte del capítulo de implementación lo describes o en qué milestone se ha aplicado principalmente.

2024-02-13 10:28 UTC, JJ commented
He observado que no se lanzan los tests de ortografía cuando cambias la allowlist. Deberías incluirla también como parte de los paths que lanzan el workflow.

2024-02-19 09:33 UTC, JJ requested changes
No sé si estaba listo para revisión, pero en todo caso estoy revisando otros aspectos que podrían ser interesantes. 
Sería conveniente, en todo caso, que limitases el ámbito de este PR sacando solo y exclusivamente lo referido a la metodología en su propio PR. Puedes sacar una rama de esta y crear un PR para luego fusionar con esta, o preferiblemente, una rama de main, llevarte sólo ese capítulo, y cuando fusiones con main fusionar con esta rama, que tendrá solamente el resto.

2024-02-19 09:33 UTC, JJ commented on doc/proyecto.tex
>  	% Desarrollo bajo sprints:
En general, los comentarios estos no parece que correspondan ni a la organización en milestones ni al guión de lo que vas a hacer. Considera eliminarlos, y usar issues o simplemente el orden del desarrollo en vez de eso.

2024-02-19 09:33 UTC, JJ commented on doc/proyecto.tex
>  	%   5. Instalación de la aplicación de manera automática
No se habla de "instalación", sino de "Despliegue". El despliegue puedes ponerlo como parte de la implementación o no.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  Las Issues son simples tareas que hay que realizar para completar los Hitos.
Los issues no son tareas, son problemas.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +La elección del diseño del sistema se basa en esta metodología, buscando una estructura que permita una implementación flexible y centrada en las necesidades del usuario.
Esta es una sección de metodología. No eliges "el diseño", eliges "la metodología que vas a usar en el diseño". En la implementación es donde tendrás que explicar cómo vas a aplicar esa metodología.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +Los diseños que conozco son Modelo Vista Controlador, Programación Orientada a Objetos, Diseño Basado en Servicios o Diseño Dirigido por el Dominio.
Por favor, trata de evitar frases como "que conozco". Y MVC no es un diseño, es una metodología de diseño. No puedes meter en el mismo saco MVC, POO y DDD. Recuerda que en la memoria hay que mostrar que se conocen bien los diferentes conceptos, y si metes DDD y POO en el mismo saco eso no va a dar una buena impresión en el tribunal. Aquí tendrías que explicar qué metodologías hay alternativas, y por qué es buena DDD en este aspecto. Mira cosas como https://www.reddit.com/r/ExperiencedDevs/comments/mgkhmf/what_alternatives_to_domaindriven_design_ddd_are/?onetap_auto=true&one_tap=true, por ejemplo.
PDO es simplemente una característica de un lenguaje que puedes usar con DDD o con cualquier otra metodología (como CRUD)

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +En este proyecto, se ha elegido el Diseño Dirigido por el Dominio (DDD) \cite{domain-drive-design} como enfoque principal, en línea con el desarrollo ágil debido a que ambos se centran en el usuario.
¿Entonces no usas PDO? ¿Ves como no son alternativas?

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +También coge pequeñas cosas de otros diseños como la Programación Orientada a Objetos para la creación de clases y objetos, y me parece una buena oportunidad para investigar y aprender nuevos diseños
La PDO *no es un diseño*. Ni siquiera es una metodología de diseño.
Por favor, trata de evitar estas afirmaciones, que en un 90% de los casos recibirán un tratamiento bastante duro por parte del #13, sobre todo si son profesores que han dado esa asignatura (una probabilidad altísima)

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +Cabe mencionar que el diseño entra en juego a partir del Hito 1 y se reflejará en la sección de Implementación,
¿por qué? Aquí estás hablando de metodología. Está claro que de la implementación hablarás cuando hables de implementación.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +más específicamente en el capítulo de diseño, donde se explicará cómo se ha aplicado el DDD en el proyecto.
No es un capítulo, sino una subsección. Pero en todo caso considera la posibilidad de eliminar esta frase.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  Esta herramienta nos permite corregir la ortografía, gramática y semántica de la documentación escrita. Se puede ejecutar la corrección a través del comando \textit{check} del Makefile,
La implementación tienes que organizarla como una serie de problemas que vas a resolver, organizados de forma conceptual o temporal. Al principio de la sección tendrás que hacer una descripción del PMV que se va a dar con ese milestone, y explicar el resto de las subsecciones cómo están organizadas.
En estas subsecciones tiene que haber una narrativa, porque es una descripción de los retos a los que se ha enfrentado uno, por lo que cada subsección tiene que enlazar con la anterior y la siguiente, y motivarse. ¿Por qué usas un IDE? ¿Por qué necesitas "herramientas de documentación" (será "generación y comprobación de documentación", ¿no?)?
Por otro lado, en *cada* herramienta tienes que mostrar que conoces las alternativas existentes y que has tomado una decisión informada sobre las mismas, pero sobre todo *por qué* has tenido que usar y elegir ese tipo de herramientas. En el caso del corrector gramatical, ¿por qué la has decidido usar ese tipo de herramienta? Nadie la usa, y menos de forma automática. ¿Qué principios aplicas a la hora de elegirla?

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +La implementación del código estará guiada por el Diseño Dirigido al Dominio, esto significa que el diseño del código se basará en el dominio del problema.
Si has explicado antes la metodología que has seguido, tendrás qu ehacer una referencia.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +De esta manera, lo primero que he hecho ha sido definir un conjunto de clases abstractas que representan conceptos del Domain Driven Design.
Esta decisión tendrás que justificarla. Ya te dije cuando lo incluiste que era una decisión que tenías que reconsiderar, simplemente porque no correspondían a un producto mínimamente viable y por tanto no son parte de un milestone 0, nunca. Tienes varias opciones aquí: simplemente no mencionarla es una. Si la mencionas, tienes que justificar, dentro del desarrollo ágil, qué valor aportan al clientey al PMV 0.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Estas clases abstractas nos aportarán valor abstrayendo las Entidades, Objetos de Valor, Agregados, Eventos y Servicio de dominio.
No tienen que aportarte valor a ti, sino al cliente. Y estás abstrayendo diferentes tipos de patrones que, de antemano, no sabes si vas a necesitar. ¿Hay algún servicio de dominio en tu problema?
Por otro lado, deberías usar algún otro tipo de convención que no sean mayúsculas para referirte a estos objetos.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  \subsection{Código}
¿El diseño no se hace con código?

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Este tipo de clases compartidas por todo el proyecto irán en un paquete llamado \textit{shared} que será importado por el resto de módulos del proyecto.
¿Estás haciendo referencia a paquetes antes de explicar la modularización del proyecto? ¿O qué lenguaje estás usando?

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Después de esto, se deben localizar los subdominios y los contextos acotados. La arquitectura del proyecto se ha dividido en módulos que representan los distintos contextos acotados.
Realmente, en DDD lo primero es precisamente esto. No estás explicando el concepto de contexto acotado ni específicamente qué estás eligiendo como "bound" (o límite) de tus contextos.

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Inicialmente, se van a crear lo mínimo necesario para el cliente, después poco a poco se irá aportando valor al producto, añadiendo más funcionalidades y mejoras.
Esto se contradice con el hecho de que has creado una serie de clases abstractas. Si no las estás usando inicialmente, no las menciones. Convendría que fueras concreto en "lo mínimo necesario". ¿Con qué historias de usuario vas a trabajar inicialmente?

2024-02-19 09:33 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  \subsubsection*{Integración Continua}
¿la integración continua no tiene que estar funcionando antes que el código? ¿Al menos en el aspecto de linting?

2024-06-23 08:55 UTC, JJ requested changes
Aparte de los nuevos comentarios, ten en cuenta lo comentado en #84 sobre justificación de las decisiones.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +La metodología se centrará en el usuario, por lo que se utilizará una planificación ágil, con el objetivo
Es al revés, el desarrollo ágil dice que hay que centrarse en el usuario. Tienes que empezar por decir el marco de desarrollo.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +La planificación que se va a emplear está basada en los {\href{https://agilemanifesto.org/iso/es/principles.html}{principios del manifiesto ágil}}
Ya has elegido el desarrollo ágil desde el principio (y convendría que hubieras puesto alguna referencia, es una de las rúbricas). Ahora tienes que seguir lo que diga el desarrollo ágil eligiendo alguna metodología de planificación que esté de acuerdo con ello.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  Buscamos un tipo de planificación que se centre en el usuario, para que el propio usuario nos aporte retroalimentación.
Pero no va a ser el caso, así que tendrás que elegir una metodología específica que no necesite de retroalimentación continua.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  Una planificación ágil nos permite adaptarnos al cambio de requisitos haciendo uso de las iteraciones y
Más bien que aproveche las oportunidades que se ofrecen. Es otra rúbrica de calificación.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  evitando caer en una documentación excesiva llena de diagramas y requisitos innecesarios.
Como tengas en el tribunal a alguien que de las asignaturas estas de ingeniería del software te crucifican. No antagonices al tribunal. Justifica lo que has elegido con referencias a artículos.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  El desarrollo ágil construye el sistema por medio de aportaciones frecuentes de código que aportan valor
Todavía no has dicho qué método de planificación vas a usar. Los que se suelen usar son Scrum o Kanban. ¿Cuál has usado tú?
Recuerda que aquí tienes que poner lo que has hecho, no es un trabajo de clase donde se pone lo que quiere uno que el profe lea.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\section{Control de versiones}
Seguimos con El uso inconsistente de Mayúsculas En títulos de secciones.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +En esta sección, nos adentramos en el concepto de User Journeys, una herramienta invaluable para entender cómo interactúan los usuarios con nuestro producto o servicio a lo largo de su ciclo de vida.
Si es invaluable tiene que haber una referencia que lo apoye.
También "invaluable" es una palabra tan poco común en español que esto apunta a que has traducido literalmente una frase del inglés, lo que inmediatamente lleva al tribunal a usar Turnitin. Trata de evitarlas.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +expresa lo que quiere el usuario del sistema por esto lo hace tan importante, se centra completamente en el
No, ese es el concepto que suelen explicar en las asignaturas de la carrera. El usuario "quiere hacer login". El usuario "quiere que los resultados se los den ordenados en una lista".
[En este artículo](https://www.linkedin.com/pulse/comenzando-con-un-trabajo-fin-de-gradom%25C3%25A1ster-%25C3%25A1gil-juan-j-merelo/?trackingId=snKNI3haQJCx4x9Q2Lod%2Fg%3D%3D) explico cómo se tienen que formular las historias de usuario: son descripciones de alto nivel del problema que tiene el usuario, sin referencia a ninguna solución, que debe salir durante el desarrollo. Es también como te lo he ido comentando.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +etiqueta y debe tener una pull request asociada para poder revisar el código.
No has dicho que vas a usar pull requests para avanzar el código. Y el tribunal no tiene por qué conocerlos.
También en todo caso enlazarlos y/o adjuntar un pantallazo de ejemplo ayuda al tribunal a entenderlo.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  \section{Control de calidad}
Estás poniendo esto al mismo nivel que "issues". Una vez más, es importante que no uses enumeraciones, sino narraciones siguiendo la lógica del desarrollo. Estás agrupando herramientas de trabajo en equipo con consideraciones generales sobre el desarrollo, como el control de calidad.
Y el control de calidad también incluye lo sissues y demás. Es una consideración general en desarrollo ágil.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +La implementación del código estará guiada por el Diseño Dirigido al Dominio, esto significa que el diseño del código se basará en el dominio del problema.
Por favor, no cierres sin hacer referencia al commit donde has solucionado el problema.

2024-06-23 08:55 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +De esta manera, lo primero que he hecho ha sido definir un conjunto de clases abstractas que representan conceptos del Domain Driven Design.
... y ya no usas las clases abstractas, y has resuelto este comentario. Convendría que reabrieras todos estos comentarios y vieras qué es lo que piden, y si están solucionados, indicar dónde se ha hecho.

2024-07-01 19:03 UTC, RubenDelgadoPareja commented on doc/secciones/05_implementacion.tex
> +De esta manera, lo primero que he hecho ha sido definir un conjunto de clases abstractas que representan conceptos del Domain Driven Design.
De acuerdo , voy a darle un repaso a todo lo modificado a esta PR cuando se mergee sobre esta la #84 . Gracias!

2024-07-01 19:19 UTC, RubenDelgadoPareja commented on doc/secciones/04_metodologia.tex
>  evitando caer en una documentación excesiva llena de diagramas y requisitos innecesarios.
Para nada es mi intención, quizás busco otra forma de expresarme pero me parece un muy buen punto del desarrollo ágil

2024-07-01 19:21 UTC, RubenDelgadoPareja commented on doc/secciones/04_metodologia.tex
>  El desarrollo ágil construye el sistema por medio de aportaciones frecuentes de código que aportan valor
Estoy en duda sobre esto, pueden aplicarse ambas no?? Supongo que empiezo a contar cuando tenga un ritmo de desarrollo constante no? Porque hasta ahora solo he tenido rachas desorganizadas ....

2024-07-01 19:31 UTC, RubenDelgadoPareja commented on doc/secciones/04_metodologia.tex
> +La planificación que se va a emplear está basada en los {\href{https://agilemanifesto.org/iso/es/principles.html}{principios del manifiesto ágil}}
He añadido un link a una web de redhat, si no es suficiente la cito

2024-07-01 20:11 UTC, RubenDelgadoPareja commented on doc/secciones/05_implementacion.tex
> +La implementación del código estará guiada por el Diseño Dirigido al Dominio, esto significa que el diseño del código se basará en el dominio del problema.
Perdona por no haberlo comentado, pero está resuelto en la PR #84 . Cuando se mergee sobre esta PR no habrá problema

2024-07-01 20:24 UTC, RubenDelgadoPareja commented on doc/secciones/04_metodologia.tex
> +etiqueta y debe tener una pull request asociada para poder revisar el código.
Está en el apartado de las issues pero no me parece mal un pantallazo

2024-07-02 11:24 UTC, JJ requested changes
Le he dado otra vuelta a este, aunque creo que no estaba listo del todo para revisión.

2024-07-02 11:24 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +La planificación que se va a emplear está basada en los {\href{https://agilemanifesto.org/iso/es/principles.html}{principios del manifiesto ágil}}
Siempre es conveniente que pongas artículos  o libros

2024-07-02 11:24 UTC, JJ commented on doc/secciones/04_metodologia.tex
>  El desarrollo ágil construye el sistema por medio de aportaciones frecuentes de código que aportan valor
Pero esas rachas las has ido haciendo a partir de issues, ¿no? ¿Has escogido los issues según su urgencia o su cantidad de trabajo? Entonces lo más parecido es kanban.
La metodología en todo caso te debe decir qué hacer a continuación.

2024-07-02 11:24 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\section{Control de versiones}
Y ahora que lo pienso, Git y GitHub es una herramienta de trabajo en equipo y de CI/CD, es mucho más que un control de versiones. Quizás podrías o dividir en dos partes (una para git, otra para github, dejando entonces este título) o bien cambiar el título para explicar que usas una herramienta de trabajo en equipo y CI/CD y ello conlleva usar git (no sé si se puede usar github con otra cosa, creo que no)

2024-07-02 11:24 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +La herramienta que yo he escogido es git y GitHub por su facilidad de uso y por su integración con otras herramientas.
Recuerda que tienes que poner siempre las opciones posibles. No se trata de que cuentes las decisiones, sino de que tienes madurez para tomar una decisión considerando todas las opciones posibles.

2024-07-02 11:24 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +El desarrollo ágil debe ser incremental y para ello se debe dividir la carga de trabajo de diferentes hitos.
... que corresponden a productos mínimamente viables y capas de abstracción en el desarrollo de software.

2024-07-02 17:01 UTC, RubenDelgadoPareja commented on doc/secciones/04_metodologia.tex
> +La planificación que se va a emplear está basada en los {\href{https://agilemanifesto.org/iso/es/principles.html}{principios del manifiesto ágil}}
De acuerdo , he buscado un libro que hay justamente en la facultad , pero sobre el link del manifiesto ágil lo veo conveniente. Es literalmente la pagina del manifiesto ágil

2024-07-02 17:04 UTC, RubenDelgadoPareja commented on doc/secciones/04_metodologia.tex
>  El desarrollo ágil construye el sistema por medio de aportaciones frecuentes de código que aportan valor
Si, finalmente voy a indicar que he usado Kanban y he dejado una captura del tablero nuevo que aporta GitHub

2024-07-02 17:47 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +La planificación que se va a emplear está basada en los {\href{https://agilemanifesto.org/iso/es/principles.html}{principios del manifiesto ágil}}
Sí, no pasa nada por mantener el link,

2024-07-03 06:42 UTC, JJ approved these changes
No creo que mejore mucho más. Si acaso al final del desarrollo se hace una revisión completa por coherencia.

2024-07-03 06:42 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +Como consecuencia de usar GitHub se "decide" escoger git, que es un sistema de control de versiones distribuido para manejar el proyecto con velocidad y eficiencia.
No es con velocidad y eficiencia, es porque no te queda otro remedio.

2024-07-03 19:04 UTC, merged