81 pruebas unitarias del modulo de paciente
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #83
Opened 2024-02-29 12:47 UTC by RubenDelgadoPareja

Se ha agregado la herramienta de Jest para la comprobación del código. 
Se han creado el test de Paciente, a medida que surjan más métodos se agregarán. 
Se ha configurado un workflow de test
Esta PR es necesaria para satisfacer la HU #13 y ofrecer un código de calidad y #5 para cerciorarnos de que los Pacientes se crean correctamente. 
El merge de esta PR cierra la issue #81

2024-02-29 12:55 UTC, RubenDelgadoPareja commented
No hacer mucho caso al prefijo (INN) de los últimos commits, me he confundido con los de otro proyecto. Perdón

2024-03-04 08:00 UTC, JJ requested changes
Para evitar problemas más adelante, deberías dedicar PRs *sólo* a la herramienta, su elección, y su configuración CI, así como el código donde lo expliques. Los tests que hagas ya se verán más adelante.

Si quieres dejar tests como pruebas de concepto, me vale, pero en todo caso la documentación tiene que irse desarrollando a la vez.

2024-03-06 19:06 UTC, RubenDelgadoPareja commented on .github/workflows/test.yml
> +          node-version: 16
No entiendo a que te refieres con que se haga un test con cada version de Node (lts, actual y desarrollo). No tiene sentido si siempre voy a usar la LTS en el proyecto...

2024-03-06 19:09 UTC, RubenDelgadoPareja commented on .github/workflows/test.yml
> +          if [ -f package-lock.json ]; then
Creo que te confundes con el archivo package.json. Este archivo se autogenera si hacemos npm install o npm ci . Por eso es la condicion , si no tenemos instalaciones de los paquetes , lo hacemos y ya podemos testear. Aunque quizás no es mala idea ejecutar siempre la instalación de los paquetes

2024-03-06 19:13 UTC, JJ commented on .github/workflows/test.yml
> +          node-version: 16
Las LTS cambian cada dos años. Y cambian a la de desarrollo, y la última LTS queda fuera. Esa github action tiene una sintaxis que permite especificar por nombre, no por versión, las versiones con las que se va a testear, y *siempre* hay que testear varias versiones, porque no sabes cuál vas a tener disponible cuando despliegues ni si una característica en la que confiéis va a deprecarse en la siguiente versión.

2024-03-06 19:30 UTC, RubenDelgadoPareja commented on package.json
>      "@nestjs/common": "^10.2.10",
La quito

2024-03-19 10:20 UTC, RubenDelgadoPareja commented
Tanto esta PR como su issue asociada #89 quedan a la espera de que haya métodos funcionales que testear

2024-07-02 19:25 UTC, RubenDelgadoPareja commented
Cierro esta PR hasta que no sea necesario el testea de ninguna funcionalidad. Ya que actualmente nos encontramos modelando el dominio del problema y no hay nada que testear.

2024-07-02 19:25 UTC, closed without merging