Documentación reformular capítulo de implementación en la memoria
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #84
Opened 2024-03-01 20:21 UTC by RubenDelgadoPareja

Esta PR ha surgido de los comentarios de la PR #79. Se ha decidido que la implementación no estaba bien estructurado y requería de un cambio. Esta PR aporta valor a la HU #13  , ya que ayuda a la narrativa y claridad de la memoria. 
Cuando esta PR se mezcle se cerrará la issue #82

2024-03-04 08:11 UTC, JJ requested changes
La escritura de la memoria tiene bastante importancia, porque con una memoria bien escrita la predisposición del tribunal a poner buena nota es mayor; una memoria con frases gramaticalmente ambiguas o con una estructura poco clara planteará una gran cantidad de preguntas.

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +El primer PMV consiste en alcanzar un repositorio inicial donde comenzar a forjar toda la arquitectura del proyecto con una planificación inicial.
¿Alguna alternativa a "alcanzar un repositorio inicial"? ¿De qué producto estamos hablando?

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +En el capítulo de metodología ya definimos el PMV a alcanzar para este hito \ref{sb:hito0}.
Si tiene subsecciones, debes introducirlas e indicar la razón por la que siguen esa secuencia.

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\subsection{Memoria}
Trata de usar títulos de subsecciones un poco más indicativos. ¿Qué es "Memoria"? ¿Toda la memoria la vas a escribir aquí?

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Para verificar activamente que lo escrito en la memoria esté correcto se ha empleado una herramienta de LaTeX llamada \href{https://github.com/sylvainhalle/textidote}{TeXtidote}.
¿Esto después de "Memoria"?

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\subsubsection*{Lenguaje de Programación}
no Uses mayúsculas Arbitrarias.

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  \subsubsection*{Integración Continua}
¿Qué sobre la integración continua? ¿Qué has hecho con ella?

2024-03-04 08:11 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\section{Hito 1: Modelado del Problema con DDD}
¿"Modelado del problema" es el PMV?

2024-03-09 17:02 UTC, RubenDelgadoPareja commented on doc/secciones/05_implementacion.tex
> +Para verificar activamente que lo escrito en la memoria esté correcto se ha empleado una herramienta de LaTeX llamada \href{https://github.com/sylvainhalle/textidote}{TeXtidote}.
He cambiado la subsección de Memoria a Herramientas para la memoria. Creo que ahora se entiende mejor , que el corrector ortográfico es una herramienta para la memoria.

2024-03-11 10:27 UTC, JJ requested changes
Has avanzado bastante, pero seguimos teniendo el problema de PRs muy largos, con partes un poco polémicas, que pueden bloquear el avance del mismo. Sería conveniente que hicieras PRs mucho más pequeños, con un issue o 2. En este caso, además, se ha detectado un problema con el diseño de los milestones, que quizás tendrías que reconsiderar.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +El primer problema es encontrar un lugar donde comenzar el desarrollo del proyecto y configuraciones de herramientas, para ello necesitamos un entorno de desarrollo integrado (\textit{IDE}).
Considera usar "una herramienta" y no "un lugar"

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +He decidido elegir Visual Studio Code para el desarrollo del proyecto debido a que tengo experiencia usándola y me siento cómodo desarrollando en este {\textit{IDE}}.
Las decisiones de herramientas nunca pueden consistir en "he decidido", sino en 
1. Necesito una herramienta con estas características
2. Estas herramientas las tienen en tal o cual medida
3. De todas estas herramientas, se ha decidido usar esta *por tal o cual razón*

En el caso de JavaScript existe WebStorm, que #13 puede conocer (no es probable, pero tampoco imposible). También #13 pide que se sepan documentar las decisiones y aprovechar las oportunidades, y es parte de la nota. Así que debes hacerlo, empezando por las primeras, que son por un lado las más importantes y por otro las que hay una probabilidad más alta que #13 lea (o conozca)

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  Otro motivo fundamental es que es gratuita, además contiene una gran cantidad de extensiones y configuraciones lo que facilita programar, también es ligero y multiplataforma.
Webstorm también lo es, aunque no es libre. De hecho, no dices la característica fundamental, y es que es software (más o menos) libre.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\subsection{Herramientas para la memoria}
¿Para qué de la memoria?

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  Me parece muy cómodo y versátil frente a otras opciones.
Que no has mencionado.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  \paragraph*{Compilación de LaTeX}
Cuando pones una lista dentro de un titular se entiende que el título de la lista es ese titular. ¿Crees que "Compilación de LaTeX" es una "Herramientas de la memoria"? Trata de hacer los elementos de orden inferior coherentes con el título que tengan, porque así van a aparecer en el índice. Si no tienes muy claro, simplemente genera el índice y mira a ver si tiene sentido las listas que aparecen ahí.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  en el ámbito académico y científico, es necesario para poder generar la documentación final, agrupando cada capítulo, sección y
No has dicho que vas a usar `make` como gestor de tareas en este caso.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +La memoria es muy importante en el desarrollo de un proyecto, ya que, es el reflejo de todo el trabajo realizado y es necesario para la evaluación del proyecto.
no se pone nunca coma después de que. ¿El corrector gramatical deja pasar esto?

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Para verificar activamente que lo escrito en la memoria esté correcto se ha empleado una herramienta de LaTeX llamada \href{https://github.com/sylvainhalle/textidote}{TeXtidote}.
¿Para qué de la memoria? ¿Esté correcto en qué sentido?

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +El código es imprescindible para el desarrollo, debemos encontrar un lenguaje que satisfaga las necesidades de la \ref{sc:planificación}.
De veras, estas frases te van a causar problemas. No digas cosas obvias, y menos para introducir la elección del lenguaje.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Además, es necesario tener un constante análisis estático para mantener un código limpio, coherente y libre de errores.
¿Por qué necesitas el análisis estático? ¿Es por la elección del lenguaje? ¿No deberías hablar de esto *después* de hablar del lenguaje? Lenguajes como Go o Raku no necesitan análisis estático.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Finalmente, para aportar valor al producto he decidido automatizar estos procesos con la integración continua, mencionado en la sección \ref{sc:control-calidad}.
Por favor, ten en cuenta el desarrollo ágil. Esto no lo "has decidido" para "aportar valor al producto". La integración continua es una de las metodologías esenciales en desarrollo ágil, y se usa para comprobar la calidad en todos sus aspectos; la calidad es una de los principios fundamentales en desarrollo ágil.
Debes intentar en el desarrollo de la memoria que se muestre que has seguido una serie de buenas prácticas y metodologías, y entiendes cuando y cómo usarlas en la práctica.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Finalmente, para aportar valor al producto he decidido automatizar estos procesos con la integración continua, mencionado en la sección \ref{sc:control-calidad}.
Por otro lado, yo no entendía esto como introducción a las subsecciones sino como explicación de las mismas. La introducción en cada subsección debe indicar qué se va a contar y por qué una sigue a la otra.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Para el desarrollo de un proyecto es esencial decidir con qué herramienta principal, en este caso el lenguaje, se va a crear. De entre mi pila de lenguajes de programación he
Una vez más, no lo plantees de esa forma. Y una vez más, "he escogido" tampoco justifica una decisión ni muestra las alternativas y por tanto no suele ser bien recibido por el tribunal.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +No se ha escogido TSLint, por el hecho de que, está obsoleta y no tiene mantenimiento, también se ha barajado SonarQube y CodeClimate.
ya he comentado arriba como tiene que hablarse de las herramientas  escogidas.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\section{Hito 1: Priorizar una cita}
Esto sigue sin ser un producto mínimamente viable.
Si el hito 0 es la infraestructura, aquí debería estar un análisis del problema, es decir, analizar las historias de usuario usando domain driven design para llegar a un lenguaje ubicuo. Sin este análisis del problema, no se puede comprender y por tanto programar la lógica de negocio.
Quizás sería conveniente que esperararas hasta tener terminado este hito para describirlo.

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Durante el primer hito del proyecto debemos de alcanzar el PMV que permita priorizar una cita por el riesgo del paciente.
Por concretar un poco más, una vez que has montado la infraestructura (hito 0) no sabes ni qué es una cita, ni qué es un paciente, ni qué es el riesgo. Hasta que no se entiendan esos conceptos (y se programen las estructuras de datos) es imposible "priorizar" (una palabra que tampoco se sabe qué significa)

2024-03-11 10:27 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +La implementación del código estará guiada por el Diseño Dirigido al Dominio, esto significa que el diseño del código se basará en el dominio del problema.
Significa más cosas, y aquí deberías añadir una cita. Y esta subsección debería ser en realidad el milestone 1.

2024-03-11 22:22 UTC, RubenDelgadoPareja commented
> Has avanzado bastante, pero seguimos teniendo el problema de PRs muy largos, con partes un poco polémicas, que pueden bloquear el avance del mismo. Sería conveniente que hicieras PRs mucho más pequeños, con un issue o 2. En este caso, además, se ha detectado un problema con el diseño de los milestones, que quizás tendrías que reconsiderar.

Me parece bien , voy a arreglar el hito 0 y el hito 1 lo documentaré cuando se termine

2024-03-13 09:20 UTC, JJ requested changes
Has mejorado algunas cosas, pero todavía deberías considerar algunos comentarios para superar este PR.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\section{Hito 0: Infraestructura inicial y documentación}
Considera poner "infraestructura y documentación inicial", si no se puede entender que *toda* la documentación va a estar aquí.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\subsection{Memoria}
Por favor, dale una vuelta a *todos* los comentarios.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\subsection{Herramientas de desarrollo}
Sé consistente con el uso de mayúsculas. Yo prefiero que no se usen, pero en otros títulos las usas. Si vas a hacerlo así, hazlo *siempre* así.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  \subsection{Entorno de Desarrollo Integrado}
Aquí estás usando mayúsculas; aparte de que estás asumiendo que se va a usar un IDE y no un editor como Neovim o emacs.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Sobre toda estas he escogido Typescript junto con Node.js, ya que da una gran robustez gracias al tipado, es un lenguaje moderno y con una gran comunidad.
Sigue sin ser una buena justificación. Recuerda
1. Criterios para elección
2. Diferentes opciones y como cumplen los criterios
3. justificación de la elección en base a los criterios.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +En TypeScript a pesar de tener un tipado fuerte, es posible que se cometan errores que no se detecten hasta que se ejecute el código, por ello es necesario un análisis estático del código.
```suggestion
En TypeScript, a pesar de tener un tipado fuerte, es posible que se cometan errores que no se detecten hasta que se ejecute el código; por ello es necesario un análisis estático del código.

```

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Para el desarrollo ágil es inprescindible garantizar la calidad, la eficiencia y sostenibilidad del código a largo plazo.
Esta frase podría ir antes de la anterior.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Las posibles herramientas a escoger son SonarQube, ESLint, TSLint, Checkmarx, PMD. Sin embargo, ESLint es la única herramienta especifica para el lenguaje escogido, TypeScript.
No has dicho qué herramienta es. Y un analizador estático de código no es lo mismo que un linter; los analizadores de código van más allá. Por favor, explica bien los conceptos para que #13 los comprenda.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Mientras que SonarQube es una herramienta más generalista y Checkmarx es una herramienta de pago. PMD es una herramienta que se utiliza para Java, por lo que no es aplicable.
Porque no es un linter. Si no es aplicable, no tienes siquiera que ponerla. Estás una vez más diciendo los criterios para no elegir algo después de decir qué has elegido. Los criterios son antes que cualquier otra cosa.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +ESLint te permite aplicar reglas personalizadas, reglas predefinidas y configuraciones de estilo para garantizar que tu código sea consistente y libre de problemas.
Si esos son los criterios, tienes que anunciarlos antes de las herramientas, y decir como lo cumple cada herramienta.

2024-03-13 09:20 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +No se ha escogido TSLint, por el hecho de que, está obsoleta y no tiene mantenimiento.
```suggestion
No se ha escogido TSLint, por el hecho de que está obsoleta y no tiene mantenimiento.

```
Nunca se pone coma después de "que"

2024-03-14 10:18 UTC, JJ requested changes
Los PRs deben ser lo más atómicos posible, para que sea fácil revisarlos y también no bloquearlos por la existencia de algún error. Aquí deberías desgajar la parte de la lista de palabras permiticas y el fichero `proyecto.tex`, y mposiblemente `04_metodologia.tex` y centrarte en la parte de implentación.
En esta parte sería también muy conveniente que pusieras cada herramienta por separado, aunque lo cierto es que todos tienen más o menos el mismo problema.

2024-03-14 10:18 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Sobre toda estas he escogido Typescript junto con Node.js, ya que da una gran robustez gracias al tipado, es un lenguaje moderno y con una gran comunidad.
Estos comentarios, de hecho, son los más importantes, porque el TFG es el conjunto de decisiones que se han tomado, por qué se han tomado, y cómo se ha justificado. Por favor, dales la importancia que merece.

2024-03-14 10:18 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +El lenguaje a escoger tiene que tener soporte en la actualidad, una gran comunidad, una gran batería de librerías, ser seguro y escalable.
¿Hay algún lenguaje que no sea escalable? (¿Y qué significa escalable en este contexto?)

2024-03-14 10:18 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  Las diferentes opciones que encontramos para el cliente o local pueden ser git, SVN, Mercurial y para el servidor donde se harán las pruebas y la integración se presentan las siguientes
Estás mezclando herramientas de control de fuentes con herramientas de integración continua. Cada una debe tener su propio apartado. `git` no es un cliente de Travis.

2024-03-14 19:04 UTC, RubenDelgadoPareja commented
> Los PRs deben ser lo más atómicos posible, para que sea fácil revisarlos y también no bloquearlos por la existencia de algún error. Aquí deberías desgajar la parte de la lista de palabras permiticas y el fichero `proyecto.tex`, y mposiblemente `04_metodologia.tex` y centrarte en la parte de implentación. En esta parte sería también muy conveniente que pusieras cada herramienta por separado, aunque lo cierto es que todos tienen más o menos el mismo problema.

Vale,  voy a intentar a partir de ahora hacer las PR mucho más cortas y atómica. En esta PR no voy a añadir nada que no tenga que ver con las herramientas de la implementación y la justificación.

2024-04-02 08:55 UTC, JJ requested changes
Por favor, trata de resolver *todos* los comentarios que se hacen. Puedes consultar en la pestaña `Files` si se quedan un poco perdidos en la pestaña general.

2024-04-02 08:55 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  en el ámbito académico y científico, es necesario para poder generar la documentación final, agrupando cada capítulo, sección y
Me temo que todavía quedan algunos comentarios sin resolver, como este.

2024-04-02 08:55 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Sobre toda estas he escogido Typescript junto con Node.js, ya que da una gran robustez gracias al tipado, es un lenguaje moderno y con una gran comunidad.
Y este sigue sin resolver.

2024-04-03 06:12 UTC, JJ requested changes
A veces puede haber comentarios en el panel de la izquierda, si es sobre cosas que ya se han revisado. Por favor, dale una vuelta a este que te he indicado.

2024-04-03 06:12 UTC, JJ commented on doc/secciones/05_implementacion.tex
>  en el ámbito académico y científico, es necesario para poder generar la documentación final, agrupando cada capítulo, sección y
No tiene mayor importancia en este caso, pero *realmente* deberías intentar mirar todos los comentarios y resolverlos.

2024-04-03 19:15 UTC, RubenDelgadoPareja commented on doc/secciones/05_implementacion.tex
>  en el ámbito académico y científico, es necesario para poder generar la documentación final, agrupando cada capítulo, sección y
Creo que ya he resuelto este comentario, he añadido que utilizo un gestor de tareas que es make y he seguido la metodología para escoger herramientas. Son las lineas 34 ,35 y 36. Si no es eso a lo que te refieres házmelo saber. 
Gracias y perdona por tanta vuelta

2024-04-04 08:08 UTC, JJ requested changes
En general, tienes que intentar cuando escribas algo leerlo y pensar si con lo escrito vas a convencer a #13 . Si lo que ves puede generar una pregunta porque no le convence, vas a perder puntos en el apartado de "justificación de las decisiones hechas" y posiblemente alguno más (y más si no respondes al gusto del tribunal)

2024-04-04 08:08 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Sin embargo, como no estamos en un proyecto real nos basaremos en criterios más generales de los lenguajes de programación, como pueden ser la seguridad, portabilidad, legibilidad, experiencia y se t
¿Crees que el tribunal va a ver bien lo de "no estamos en un proyecto real"?

2024-04-04 08:08 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Los lenguajes que cumplen este criterio son los siguientes: JavaScript, TypeScript, Java, Ruby, C++, Python. Partiendo de la experiencia, estos son los lenguajes que conozco.
Una de las preguntas que más hace el tribunal es "¿por qué no lo has hecho con (lenguaje X que es el que doy en mi asignatura, generalmente Java o Python)?". Los dos principales lenguajes con los que tienes que confrontar tu elección es con estos. Y conviene que uses criterios que sean objetivos y que *realmente* distingan el lenguaje elegido frente a otros. ¿Qué distingue TypeScript de Python (y, de camino, también de JavaScript)? ¿Qué distingue TypeScript de Java? Eso es, principalmente, lo que tienes que tratar de justificar aquí. 
Con generalidades como "portabilidad", tienes que Java también es portable, y C++ también existe para cualquier plataforma. Con legibilidad, no creo que puedas convencer a nadie que TypeScript es más legible que Python (y no tratándose de un criterio objetivo, también lo vas a tener jodido probando que es más legible que Java).

2024-06-23 08:31 UTC, JJ requested changes
Enunciar las decisiones es una de las rúbricas más importantes a la hora de calificar. En el [objetivo 3 de IV](https://jj.github.io/IV/documentos/proyecto/3.Automatizar) indicamos la forma correcta de proceder en este sentido, es decir, como justificar la decisión. Por favor, échale un vistazo. De camino, ese objetivo también tiene enlaces sobre como justificar el uso de gestores de tareas para este tema.
Por cierto, que una decisión que no se incluye es el elegir un runtime para TypeScript. Aunque hasta hace un año y pico sólo teníamos node, ahora está también bun. Y deno, aunque este último tiene ciertas variaciones a la hora de trabajar con bibliotecas, así que no es 100% compatible.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +La implementación del software se ha dividido en hitos. Cada hito representa un producto mínimamente viable que se publicará.
La planificación se indica en el capítulo correspondiente. Si has hecho referencia a los hitos ahí, haz aquí una referencia a ese capítulo. Si no lo has hecho, tendrías que hacerla, preferiblemente en otro PR diferente.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +El PMV del hito 0 es un repositorio inicial formado por una documentación y un conjunto de herramientas configuradas para el desarrollo del proyecto.
El concepto de PMV tendrías ya que haberlo explicado. Conviene también que expliques por qué lo llamas hito 0.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Aunque inicialmente tengo que aclarar dónde se completa tanto documentación como desarrollo.
No entiendo muy bien esta frase.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Las herramientas que cumplen con la necesidad pueden ser Visual Studio Code, Atom, Sublime Text, WebStorm, etc.
No enuncies las herramientas, di primero qué es lo que necesitas de la herramienta.
La secuencia en la descripción de la elección de una herramienta siempre es la misma.
1. Enumeración de los requisitos y características de la herramienta .
2. Enumeración de los criterios de búsqueda de la misma.
3. Decir cada una de esas herramientas como cubre los requisitos
4. Elección *objetiva* de una de ellas. 

Aquí has metido editores (Sublime Text) con IDEs genéricos (VS Code) con IDEs específicos (WebStorm) con otros que están más bien obsoletos (Atom). Si pones varias herramientas irrelevantes y una relevante, la elección va a estar clara, pero también que no has seguido un criterio objetivo para elegir la herramienta, sino que has escogido la que ya tenías.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Visual Studio Code destaca por su ligereza, multiplataforma, gran cantidad de extensiones y configuraciones, además de ser gratuita, no como WebStorm.
No has mencionado si es software libre o no, ni si vas a tener una preferencia por software libre en las herramientas. WebStorm, por otro lado, es gratis para estudiantes. En cualquier caso, los criterios *tienes que elegirlos de antemano*.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\paragraph*{Generación de la memoria}
¿Por qué usas paragraph y no `subsubsection`?

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +La herramienta \href{https://github.com/sylvainhalle/textidote}{TeXtidote} nos permite corregir la ortografía, gramática y semántica de la documentación escrita. Se puede ejecutar la corrección a tra
Cuando elijas herramientas, tienes que explicar que se enmarcan dentro del desarrollo ágil y su preocupación por la calidad. En este caso, tienes que hacer énfasis en que esto trata de asegurar la calidad de la memoria evitando errores gramaticales y de ortografía.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Finalmente, tenemos una tarea a ejecutar en el Makefile para cada herramienta, \textit{all} para generar la memoria y \textit{check} para revisarla.
Esto corresponde a la buena práctica de "configuración en el entorno", que es uno de los 12 pasos de la 12-step app. Cuando tomes alguna decisión *tienes que justificarla* en el marco de las buenas prácticas y tipo de desarrollo elegido.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Para el desarrollo ágil es imprescindible garantizar la calidad, la eficiencia y sostenibilidad del código a largo plazo.
No te cortes en repetir párrafos como este en otros lugares. 
En todo caso no parece que el análisis estático esté al mismo nivel de abstracción que el lenguaje de programación; si acaso, este sería un apartado de aquél. 
Intenta que el nivel de abstracción de las secciones de un nivel sea siempre el mismo.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +En TypeScript, a pesar de tener un tipado fuerte, es posible que se cometan errores que no se detecten hasta que se ejecute el código; por ello es necesario un análisis estático del código.
Con esto ya estás indicando que depende de la sección anterior.

2024-06-23 08:31 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +\subsubsection*{Integración continua}
Tienes muchas subsecciones y eso dificulta seguir el hilo de razonamiento de esta sección. Por ejemplo, hablas de herramientas de control de calidad antes de hablar de cómo vas a lanzar esas herramientas automáticamente.
Deberías intentar agrupar estas sub-sub-secciones de alguna forma lógica, que siga niveles de abstracción o la secuencia temporal de las decisiones tomadas.
Recuerda que la memoria es el conjunto de decisiones que has tomado. Tiene que ser una historia de superación de obstáculos. "Me encontré este obstáculo, lo superé de esa forma". Es más fácil para el tribunal leerlo así, y también para ti a la hora de presentarlo.

2024-06-28 07:04 UTC, JJ requested changes
Alguna cosa más, pensaba que no lo había revisado.

2024-06-28 07:04 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\label{sc:diseño}
Por favor, intenta hacer estos cambios fuera del PR. Añaden trabajo al mismo, y realmente no necesitan ninguna revisión.

2024-06-28 07:04 UTC, JJ commented on doc/secciones/05_implementacion.tex
> +Con esta herramienta se ha configurado un workflow que se ejecuta en cada push a la rama principal, en el que se ejecutan los test, el linter y el corrector ortográfico, ya mencionado en la sección d
Tendrías que explicar también qué es un workflow; no todo el mundo en #13 lo conoce. Usa referencias si es necesario.

2024-06-29 16:29 UTC, RubenDelgadoPareja commented on doc/secciones/05_implementacion.tex
> +La implementación del software se ha dividido en hitos. Cada hito representa un producto mínimamente viable que se publicará.
Justo en la siguiente línea tengo la referencia a ese capitulo pero lo cambio a esta línea , ya que es la primera vez que se mencionan los hitos

2024-07-03 19:05 UTC, RubenDelgadoPareja commented
Al haber mergeado la PR #79 sobre develop cambiamos a develop donde haremos el merge

2024-07-17 17:21 UTC, merged