Modelado de objetos de valor para una cita
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #94
Opened 2024-03-19 20:40 UTC by RubenDelgadoPareja

Esta PR trata de solucionar el problema #91 que ayuda con la HU #19 .
Inicialmente se han creado los objetos de valor descritos en #91.
Se ha creado ya para poder ir corrigiéndola. Habrá que añadir una breve descripción en el capitulo de la implementación
pero antes deberían de mergearse las siguients PRs #84 y #79

2024-03-20 08:15 UTC, JJ requested changes
De veras tendrías que replantearte si merece la pena crear 3 ficheros y no sé cuantas clases para un objeto valor que esencialmente tiene dos o tres variables de instancia.

2024-03-20 08:15 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
> +  appointmentDate: AppointmentDate;
¿En qué se diferencia un AppointmentDate de un `Date`?

2024-03-20 08:15 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
>  export class Appointment extends Entity<AppointmentProps> {
De veras que no entiendo todo esto. Un producto mínimamente viable debe tener lo mínimo necesario para que algo sea un modelo válido. Estás creando tres ficheros para algo que es básicamente una clase con tres o cuatro variables de instancia. ¿De veras crees que es necesario?
Yo entiendo que quieras "poner en valor" las clases abstractas que has creado antes, pero también en su momento te expresé mi excepciticismo con la utilidad de las mismas...

2024-03-20 08:15 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
> +    props.confirmed = false;
¿Tienes un constructor y un `create`? ¿Y qué significa esto de `confirmed`? ¿Qué valor aporta al usuario?
¿Te das cuenta que en este momento tienes como tres o cuatro IDs diferentes, una para propos, otra para Appointment?

2024-03-20 10:59 UTC, RubenDelgadoPareja commented on src/modules/appointment/domain/appointment.ts
>  export class Appointment extends Entity<AppointmentProps> {
Realmente no veo que sea necesario , como nunca he hecho DDD en la práctica estuve investigando al respecto y pensé que era buena idea. Pero voy a rectificar ...

2024-03-21 11:38 UTC, RubenDelgadoPareja commented on src/modules/appointment/domain/appointment.ts
> +    props.confirmed = false;
El confirmed tenía pensado que fuera una atributo ara comprobar que se ha confirmado la cita por parte del Paciente, pero la voy a quitar y en el futuro se añade , cuando se haga ese método. Los IDs repetidos se han refactorizado en la PR #95 . Respecto al método create quiero que añadir las validaciones de creación, aunque como todavía no se han desarrollado voy a quitar también el create.

2024-03-21 18:34 UTC, JJ reviewed
Gracias por el esfuerzo, pero creo que todavía tendrás que intentar simplificar lo más posible.

2024-03-21 18:34 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
> +  appointmentType: AppointmentType;
¿Has probado a hacer que esto sea directamente un AppointmentTypeEnum? ¿No te simplificaría todo el código? El código con menos errores es el que no se hace.

2024-03-21 18:34 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
>    id: UniqueEntityID;
Los objetos valor no tienen ID, su valor es simplemente la combinación de variables de instancia que tienen.

2024-03-21 18:34 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
>  export class Appointment extends Entity<AppointmentProps> {
... y de hecho, ¿has pensado en meter todo como variable de instancia de Appointment, que no extienda ninguna otra cosa?
¿Tu modelo del problema te dice que vas a manejar todas las Entity de forma uniforme? ¿Va a haber algún agregado que las use todas o busque en todas?
Mírate el principio de sustitución de Liskov, que es la L de SOLID. Dice que cualquier clase base puede ser usada en lugar de cualquier clase derivada. Eso es un principio que también es restrictivo: si no vas a usar la clase base en lugar de la clase derivada (por ejemplo, usando un agregado para todas las Entity, independientemente de su instanciación), *no es necesario crear una clase derivada*. El ejercicio académico de crear una jerarquía de clases en el contexto de desarrollo ágil tiene solo el interés justo.

2024-03-22 17:09 UTC, RubenDelgadoPareja commented on src/modules/appointment/domain/appointment.ts
>  export class Appointment extends Entity<AppointmentProps> {
Lo que has comentado de quitar las clases abstractas ya se ha llevado a cabo en la PR https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/pull/95 aunque también voy a hacer aqui el cambio y dejar los atributos como variables de instancia

2024-04-02 06:59 UTC, JJ requested changes
El problema principal es que no veo cómo se puede trabajar con #19 con este modelo de cita. ¿Qué elementos de esta estructura de datos permite priorizar una cita o no? En este milestone es esencial la modelización del espacio del problema, y para ello es esencial que se entienda las características del mismo y se reflejen en las estructuras de datos usadas.

2024-04-02 06:59 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
> +    private readonly id: number,
Creo que ya te lo he dicho, pero por favor entiende por qué los objetos valor no tienen ID y por qué es así. Puedes mirar también [este artículo](https://enterprisecraftsmanship.com/posts/dont-use-ids-domain-entities/) (que de hecho, dice que tampoco las entidades deben tenerlo).
Pero no hace falta que mires el artículo. ¿Necesitas ese ID para algo? ¿Cómo lo vas a usar?

2024-04-02 06:59 UTC, JJ commented on src/modules/appointment/domain/appointment.ts
> +    private readonly confirmed: boolean = false,
Los [objetos valor son inmutables](https://www.linkedin.com/pulse/descubre-el-poder-de-los-objetos-valor-en-desarrollo-flores-arriaga--izmmc/?originalSubdomain=es) Eso significa que una vez creados no cambian de valor. Pero también significa que la mutabilidad se gestiona a otro nivel, el nivel de las entidades (otro concepto de DDD). El que esté confirmado o no depende de la lógica de negocio, que vamos a gestionar a otro nivel.

2024-04-02 19:59 UTC, RubenDelgadoPareja commented
> El problema principal es que no veo cómo se puede trabajar con #19 con este modelo de cita. ¿Qué elementos de esta estructura de datos permite priorizar una cita o no? En este milestone es esencial la modelización del espacio del problema, y para ello es esencial que se entienda las características del mismo y se reflejen en las estructuras de datos usadas.

Estoy totalmente de acuerdo, pero realmente esa es la HU que "resuelve" la necesidad del usuario. Como el modelado del dominio es algo que no influye al usuario o cliente no sabría como crear una HU que la justifique correctamente. Había pensado en que la propia #19 darle una explicación a todo. Por ejemplo, mencionar que para poder cumplir esa HU deben de solucionarse problemas anteriores como la representación del Paciente y la cita en el sistema. Voy a darle una vuelta, también creo que la HU realmente no será asi, debería de ser que un Paciente tenga una prioridad y seguir la línea de los Users Journeys (El usuario se registraba y con una serie de preguntas se le asignaba una prioridad )

2024-04-03 06:13 UTC, JJ commented
El modelado del problema tiene que modelar lo que haya en una o todas las historias de usuario. No existe "el problema" sin lo que se describe en las mismas.

2024-06-22 18:01 UTC, closed without merging