Modelo de paciente - Atributos de un paciente
RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica pull request #98
Opened 2024-04-01 16:22 UTC by RubenDelgadoPareja

Esta PR resuelve el problema #97 , el cual consiste en encontrar unos atributos que definan las características principales de un paciente en el sistema. Además esta tarea ayuda a solucionar el issue #96 y por consecuencia contribuye a la HU #19

2024-04-02 06:46 UTC, JJ commented
Mira por favor el comentario en #19 y en #97. Las historias de usuario son esenciales, y son la base de todo el desarrollo de la aplicación. Mira por favor [este objetivo en IV](http://jj.github.io/IV/documentos/proyecto/1.Planificacion). También [este artículo](https://www.linkedin.com/pulse/los-issues-y-su-importancia-en-la-organizaci%25C3%25B3n-de-un-proyecto-merelo/?trackingId=oxMGgGtJT6uJdJOQWvICBQ%3D%3D) sobre qué constituye un issue y cómo se pueden usar para organizar el desarrollo.

2024-07-08 08:41 UTC, JJ requested changes
No sé si estás usando CoPilot para generar código; lo de generar todos los getters para una clase es muy de CoPilot. En ese caso, te rogaría que dejaras de hacerlo, porque entre otras cosas rompen la encapsulación, no separan el interfaz de implementación, no siguen la norma en desarrollo ágil de usar sólo el código que necesita el cliente, pero finalmente es que tengo que revisarlo yo, que no uso IA para revisar los PCs. En una lucha de generación de código contra revisión del mismo tengo todas las de perder.

2024-07-08 08:41 UTC, JJ commented on src/modules/patient/domain/patient.ts
> +  id: number;
¿Necesitas un ID? ¿No hay nada en la descripción del paciente que actúe como identificador único?

2024-07-08 08:41 UTC, JJ commented on src/modules/patient/domain/patient.ts
> +  ssc: string;
Si esto es el número de seguridad social, que también es único según el paciente, ¿para qué necesitas el dni?

2024-07-08 08:41 UTC, JJ commented on src/modules/patient/domain/patient.ts
> +  get name(): string {
De veras, debéis intentar evitar poner todos los getters. Para empezar, no son parte del modelo, pero para seguir, es que no hacen falta.

2024-07-08 17:17 UTC, RubenDelgadoPareja commented
> No sé si estás usando CoPilot para generar código; lo de generar todos los getters para una clase es muy de CoPilot. En ese caso, te rogaría que dejaras de hacerlo, porque entre otras cosas rompen la encapsulación, no separan el interfaz de implementación, no siguen la norma en desarrollo ágil de usar sólo el código que necesita el cliente, pero finalmente es que tengo que revisarlo yo, que no uso IA para revisar los PCs. En una lucha de generación de código contra revisión del mismo tengo todas las de perder.

Si que lo tengo. Me parece razonable lo desactivaré

2024-07-08 17:51 UTC, JJ commented
> > No sé si estás usando CoPilot para generar código; lo de generar todos los getters para una clase es muy de CoPilot. En ese caso, te rogaría que dejaras de hacerlo, porque entre otras cosas rompen la encapsulación, no separan el interfaz de implementación, no siguen la norma en desarrollo ágil de usar sólo el código que necesita el cliente, pero finalmente es que tengo que revisarlo yo, que no uso IA para revisar los PCs. En una lucha de generación de código contra revisión del mismo tengo todas las de perder.
> 
> Si que lo tengo. Me parece razonable lo desactivaré

No hace falta que lo desactives; puedes ser bastante más productivo con él. Pero trata de que te genere sólo código que tú le pidas, o solo una o dos líneas de una vez. Para los tests es inmensamente útil, por ejemplo. En todo caso, revisa lo generado y mira si sigue las buenas prácticas y el estadio de desarrollo en el que estés.

2024-07-08 18:01 UTC, JJ requested changes
Has reescrito gran parte, pero has dejado algunos aspectos que se habían comentado. En todo caso, el problema es que debes de abordar la modelización usando DDD (o domain mapping, o cualquier otra metodología) de todo el problema en general para hallar los tipos más adecuados para representar cada cosa.

2024-07-08 18:01 UTC, JJ commented on src/modules/patient/domain/patient.ts
> +  symptomForm: unknown;
Exactamente igual. DDD es un proceso en cascada en el que vas modelizando partes del problema en función de otras partes, hasta que encuentras una parte del mismo que no depende de ninguna otra. esto tiene que estar regido por una serie de issues que desarrollen historias de usuario donde se contextualice, restrinja y parametrice el problema.

2024-07-08 18:01 UTC, JJ commented on src/modules/patient/domain/patient.ts
> +  static create(props: PatientInputProps): Patient {
¿Qué aporta esto frente a un constructor público?

2024-07-08 18:30 UTC, RubenDelgadoPareja commented on src/modules/patient/domain/patient.ts
> +  turn: unknown;
Estoy de acuerdo , en principio voy a eliminar estos campos , cuando sea necesario se añadirán correctamente

2024-07-08 18:32 UTC, JJ requested changes
¿Hay alguna razón para que los constructores sean privados?

2024-07-08 18:32 UTC, JJ commented on src/modules/patient/domain/patient.ts
> +  private constructor(
¿Por qué es privado el constructor?

2024-07-10 18:15 UTC, JJ approved these changes
:+1:

2024-07-10 20:20 UTC, merged